### ISSUE TITLE
No code completion when typing an annotation without a class below it

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#100]
I'm at the bottom of my file. I want to make a new class, but first I'm typing my annotation.

![screen shot 2015-07-20 at 5 15 04 pm](https://cloud.githubusercontent.com/assets/5479/8790440/facaacca-2f02-11e5-9a36-33df34c796a7.png)

I don't experience code completion here.

Once I type my class boilerplate, and return to writing annotations, I see annotation code completion options.

**Comment by devoncarew** [comment]
@danrubel

**Comment by sethladd** [comment]
I admit this one is a bit far fetched... I don't know how common it is to start writing an annotation without it attached to anything. Feel free to close this if it's not an Atom-specific issue.

**Comment by devoncarew** [comment]
It is analysis server specific - it would be better filed over there. Once there's a fix in the AS we'll pick it up.

**Comment by devoncarew** [comment]
@sethladd, can you move this issue over to the SDK repo?

**Comment by sethladd** [comment]
Closing because a bug was opened on the SDK
