### ISSUE TITLE
Manual format remove all visual hint/warning/errors

### ISSUE THREAD

**Issue by a14n** [dart-atom/dartlang#1038]
When you manually format the content (and when the ouput is different from the input) the underlines on the code completly disappear although the _Error panel_ still lists the issues.

To repro:
- create a dart file with the followning content:
```dart
main(){   int i = ""; 
}
```
- you should see 2 issues with underlines over the code for:
  - _Warning_ : A value of type 'String' cannot be assigned to a variable of type 'int'
  - _Info_ : The value of the local variable 'i' is not used
- format the file with Ctrl+Alt+B (on linux)
- bug : the list still contains the 2 issues but the underlines have disappear.

Atom 1.7.3, dartlang 0.6.25, SDK 1.16.0 running on linux.

**Comment by mezoni** [comment]
This problem already posted a 3 day ago but still does not have any reaction from developers.
Pluging GUI not correctly displays information obtained from analisis server

**Comment by mezoni** [comment]
I have a very negative attitude to the software when the developers are reluctant to respond to detected errors.

**Comment by a14n** [comment]
Trying to provide a simple reproduction scenario can help a lot to shorten the lifetime of an issue. I hope the fix of the current issue will also fix yours.

**Comment by mezoni** [comment]
@a14n 

Yes, of course, your issue also helpful and important and adds more (additional) information.
Problem only in that the similar issue has not reaction from developers.
P.S.
To reproduce it (this concrete problem) does not need a special case becuase it (problem) reproduces itself every time (every day, every hour, every munte).
To reproduce it need still try to use this plugin and you will get this problem in the next minutes.

**Comment by a14n** [comment]
Not reproduce with Atom 1.7.3, dartlang 0.6.**29**, SDK 1.16.0 running on linux.
