### ISSUE TITLE
Syntax highlighting is very slow for large files

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#104]
Opening big files like ast.dart from analyzer, or element.dart from analyzer (via Jump to definition) shows a multi-second lag for syntax highlighting.

**Comment by sethladd** [comment]
Maybe related:

![screen shot 2015-07-21 at 9 37 40 am](https://cloud.githubusercontent.com/assets/5479/8806577/293fc368-2f8c-11e5-9da1-e9f7acc03747.png)
![screen shot 2015-07-21 at 9 37 33 am](https://cloud.githubusercontent.com/assets/5479/8806576/293ee484-2f8c-11e5-88dd-1adb89667fab.png)

**Comment by devoncarew** [comment]
Not sure is there's a tracking bug, but this is an issue in core Atom.
