### ISSUE TITLE
"find references" often doesn't finish

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#1047]
Scenario:
- Select "Find References" on a symbol in a Dart file.
- References sidebar appears
- It shows "searching..."
- No further results ever appear.

I don't see any obvious difference in the logs between a search that succeeds and one that fails.

In the JavaScript console, I see:
 jobs: starting job Find references
 --> search.findElementReferences
jobs: finished job Find references
 <-- a "result" response
 <-- a "search.results" event

Once it stops working, usually (but not always) I have to "reanalyze sources" to get it working again. Then it works once or twice (maybe) and stops working again.

Atom 1.7.4, dartlang 0.6.27
Dart SDK 1.17.0-dev.2.0

**Comment by skybrian** [comment]
After closing and opening the file, sometimes it works once then fails again. I don't see an obvious pattern, actually - it's pretty random.

**Comment by devoncarew** [comment]
It looks like for this to happen, the analysis server is responding with a result object for the references query. We then listen for a stream of SearchResult objects with the indicated id, collecting the results until one of the objects has a `isLast` field set to true. So, for some reason we're not getting that last `isLast` == true event.

@skybrian, is this what you're seeing in the logs? I assume you have the logging in atom turned up to finer.

**Comment by skybrian** [comment]
It looks like every search.results event being sent has isLast set to true. That is, I see no results for:

grep 'search\.results' dartanalyzer.log | grep -v '"isLast"::true'

**Comment by skybrian** [comment]
Not seeing it at home on my Mac laptop.
Atom 1.8.0, dartlang 0.6.27
Dart SDK 1.17.1

**Comment by skybrian** [comment]
I don't see any difference in the instrumentation log. Here's a sample log when working:

<pre>
1466811858203:Req:{"id"::"62","method"::"search.findElementReferences","params"::{"file"::"[redacted]","offset"::1849,"includePotential"::false}}
1466811858204:Res:{"id"::"62","result"::{"id"::"1","element"::{"kind"::"FUNCTION","name"::"waitForAnalysis","location"::{"file"::"[redacted]","offset"::1849,"length"::15,"startLine"::58,"startColumn"::10},"flags"::0,"parameters"::"()","returnType"::"Future<dynamic>"}}}
1466811858206:Noti:{"event"::"search.results","params"::{"id"::"1","results"::[{"location"::{"file"::"[redacted]","offset"::2616,"length"::15,"startLine"::82,"startColumn"::11},"kind"::"INVOCATION","isPotential"::false,"path"::[{"kind"::"FUNCTION","name"::"main","location"::{"file"::"[redacted]","offset"::1525,"length"::4,"startLine"::47,"startColumn"::1},"flags"::8,"parameters"::"()","returnType"::"dynamic"},{"kind"::"COMPILATION_UNIT","name"::"check_greentea.dart","location"::{"file"::"[redacted]","offset"::0,"length"::0,"startLine"::1,"startColumn"::1},"flags"::0},{"kind"::"LIBRARY","name"::"","location"::{"file"::"[redacted]","offset"::-1,"length"::0,"startLine"::1,"startColumn"::0},"flags"::0}]},{"location"::{"file"::"[redacted]","offset"::2902,"length"::15,"startLine"::93,"startColumn"::13},"kind"::"INVOCATION","isPotential"::false,"path"::[{"kind"::"FUNCTION","name"::"main","location"::{"file"::"[redacted]","offset"::1525,"length"::4,"startLine"::47,"startColumn"::1},"flags"::8,"parameters"::"()","returnType"::"dynamic"},{"kind"::"COMPILATION_UNIT","name"::"check_greentea.dart","location"::{"file"::"[redacted]","offset"::0,"length"::0,"startLine"::1,"startColumn"::1},"flags"::0},{"kind"::"LIBRARY","name"::"","location"::{"file"::"[redacted]","offset"::-1,"length"::0,"startLine"::1,"startColumn"::0},"flags"::0}]},{"location"::{"file"::"[redacted]","offset"::3098,"length"::15,"startLine"::101,"startColumn"::13},"kind"::"INVOCATION","isPotential"::false,"path"::[{"kind"::"FUNCTION","name"::"main","location"::{"file"::"[redacted]","offset"::1525,"length"::4,"startLine"::47,"startColumn"::1},"flags"::8,"parameters"::"()","returnType"::"dynamic"},{"kind"::"COMPILATION_UNIT","name"::"check_greentea.dart","location"::{"file"::"[redacted]","offset"::0,"length"::0,"startLine"::1,"startColumn"::1},"flags"::0},{"kind"::"LIBRARY","name"::"","location"::{"file"::"[redacted]","offset"::-1,"length"::0,"startLine"::1,"startColumn"::0},"flags"::0}]}],"isLast"::true}}
</pre>

Not working:
<pre>
1466813837287:Req:{"id"::"63","method"::"search.findElementReferences","params"::{"file"::"[redacted]","offset"::1849,"includePotential"::false}}
1466813837288:Res:{"id"::"63","result"::{"id"::"2","element"::{"kind"::"FUNCTION","name"::"waitForAnalysis","location"::{"file"::"[redacted]","offset"::1849,"length"::15,"startLine"::58,"startColumn"::10},"flags"::0,"parameters"::"()","returnType"::"Future<dynamic>"}}}
1466813837290:Noti:{"event"::"search.results","params"::{"id"::"2","results"::[{"location"::{"file"::"[redacted]","offset"::2616,"length"::15,"startLine"::82,"startColumn"::11},"kind"::"INVOCATION","isPotential"::false,"path"::[{"kind"::"FUNCTION","name"::"main","location"::{"file"::"[redacted]","offset"::1525,"length"::4,"startLine"::47,"startColumn"::1},"flags"::8,"parameters"::"()","returnType"::"dynamic"},{"kind"::"COMPILATION_UNIT","name"::"check_greentea.dart","location"::{"file"::"[redacted]","offset"::0,"length"::0,"startLine"::1,"startColumn"::1},"flags"::0},{"kind"::"LIBRARY","name"::"","location"::{"file"::"[redacted]","offset"::-1,"length"::0,"startLine"::1,"startColumn"::0},"flags"::0}]},{"location"::{"file"::"[redacted]","offset"::2902,"length"::15,"startLine"::93,"startColumn"::13},"kind"::"INVOCATION","isPotential"::false,"path"::[{"kind"::"FUNCTION","name"::"main","location"::{"file"::"[redacted]","offset"::1525,"length"::4,"startLine"::47,"startColumn"::1},"flags"::8,"parameters"::"()","returnType"::"dynamic"},{"kind"::"COMPILATION_UNIT","name"::"check_greentea.dart","location"::{"file"::"[redacted]","offset"::0,"length"::0,"startLine"::1,"startColumn"::1},"flags"::0},{"kind"::"LIBRARY","name"::"","location"::{"file"::"[redacted]","offset"::-1,"length"::0,"startLine"::1,"startColumn"::0},"flags"::0}]},{"location"::{"file"::"[redacted]","offset"::3098,"length"::15,"startLine"::101,"startColumn"::13},"kind"::"INVOCATION","isPotential"::false,"path"::[{"kind"::"FUNCTION","name"::"main","location"::{"file"::"[redacted]","offset"::1525,"length"::4,"startLine"::47,"startColumn"::1},"flags"::8,"parameters"::"()","returnType"::"dynamic"},{"kind"::"COMPILATION_UNIT","name"::"check_greentea.dart","location"::{"file"::"[redacted]","offset"::0,"length"::0,"startLine"::1,"startColumn"::1},"flags"::0},{"kind"::"LIBRARY","name"::"","location"::{"file"::"[redacted]","offset"::-1,"length"::0,"startLine"::1,"startColumn"::0},"flags"::0}]}],"isLast"::true}}
</pre>

**Comment by devoncarew** [comment]
Hmm, possibly some race condition in atom? I'll take a look.
