### ISSUE TITLE
send client id and version to analysis server

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#1050]
I noticed that IDEA sends these flags when it starts the analysis server:

        "--client-id=IntelliJ_IDEA",
        "--client-version=IU-145.971",

Could the Atom plugin set these flags as well? (It's useful for logging.)

**Comment by devoncarew** [comment]
Easy enough :)

**Comment by devoncarew** [comment]
And, in the interest of full disclosure:

https://github.com/dart-atom/dartlang/blob/master/lib/analysis_server.dart#L566

Patches welcome :)

**Comment by skybrian** [comment]
Thanks!
