### ISSUE TITLE
Toolbar visual bug with Atom Material UI

### ISSUE THREAD

**Issue by kaendfinger** [dart-atom/dartlang#1057]
When I use the Atom Material UI theme, the toolbar has a visual bug. Not sure how to fix this.

<img width="1679" alt="image 2016-06-29 at 10 16 29 am" src="https://cloud.githubusercontent.com/assets/2130849/16461727/cb863142-3de2-11e6-9b1b-28a50a5c477c.png">

**Comment by devoncarew** [comment]
What platform is this for? There are some small styling differences between the OSes.

You can open devtools in atom; you might try and see if there are any offending styles you can disable to get better behavior, or style additions to fix the issue.

**Comment by kaendfinger** [comment]
This in particular is on Mac OS X 10.11.6 - I'll check that out and see what happens.

**Comment by kaendfinger** [comment]
Looks like the styles from atom-toolbar are the cause.

<img width="325" alt="image 2016-06-29 at 3 04 52 pm" src="https://cloud.githubusercontent.com/assets/2130849/16470416/ee13bfcc-3e0a-11e6-851f-8f571a39db95.png">

**Comment by kaendfinger** [comment]
Moved to https://github.com/dart-atom/atom-toolbar/issues/8
