### ISSUE TITLE
Switch with enum code warnings not consistent with dartpad

### ISSUE THREAD

**Issue by mehmetf** [dart-atom/dartlang#1067]
The following code produces no warnings on dartpad:

```dart
enum TestEnum {
  VAL1,
  VAL2
}

int f(TestEnum val) {
  switch (val) {
    case TestEnum.VAL1:
      return 0;
    case TestEnum.VAL2:
      return 1;
  }
}
```

but with Atom:

![image](https://cloud.githubusercontent.com/assets/6687929/16882111/286a77d8-4a72-11e6-8693-0c001ea54e45.png)

Perhaps dartpad does not show "info" level warnings by default but I wanted to highlight this discrepancy.

**Comment by eseidelGoogle** [comment]
FYI @devoncarew this was a request from Flutter's customer:leafy at our meeting just now.

**Comment by devoncarew** [comment]
closing this item - re-filed against the sdk repo.
