### ISSUE TITLE
add a close button to the analysis server status window (was: Cannot dismiss analysis server status window)

### ISSUE THREAD

**Issue by zanderso** [dart-atom/dartlang#107]
Steps to repro:
1. Packages > Dart > Show Analysis Server Status
2. Try to make status window go away.

What happens:
Window does not go away.

What should happen:
Window should go away.

**Comment by devoncarew** [comment]
You can dismiss it by hitting `escape`. That said, we should add a close button :)

**Comment by zanderso** [comment]
Of course escape works for me only after I file the issue =) A little [x] would be good, yah.

**Comment by devoncarew** [comment]
I'll re-purpose this issue -

**Comment by radicaled** [comment]
@devoncarew 

Looks like #119 fixed this -- verify and close issue if so?

**Comment by devoncarew** [comment]
Yup, fixed.
