### ISSUE TITLE
Analyzer not working after SDK build.

### ISSUE THREAD

**Issue by B3rn475** [dart-atom/dartlang#1072]
If I use the sdk I build myself after each build the editor start sending errors.
Only solution restart the editor.
Would it be possible to have a "hot swap" to avoid this problem?

Atom 1.8.0, dartlang 0.6.33, SDK 1.19.0-edge.8fef08717fe9c4af48cc9666761fe68996bffd2d running on linux.

**Comment by devoncarew** [comment]
I don't this this is a use case that many users would run into :) When working on atom itself, I end up restarting it frequently. On mac the keybinding is ctrl-option-cmd-L; I'm not sure what it is on linux.
