### ISSUE TITLE
F1 does not show dartdoc or do anything else

### ISSUE THREAD

**Issue by zanderso** [dart-atom/dartlang#108]
Steps to repro:
1. Press F1

What happens:
Nothing

What should happen:
Something

**Comment by zanderso** [comment]
It seems that pubspec.yaml possibly could not be found. Something more useful than silent failure would have been nice here. The same problem occurred with F3, jump to definition.

**Comment by zanderso** [comment]
F1 and F3 appear to work only if the pubspec.yaml is at the root of the project folder. If it is deeper inside somewhere, then it can't be found, and these don't work.

**Comment by devoncarew** [comment]
Can you tell me a bit more about your project structure, and what folder you opened? We currently try and locate dart projects by scanning down through the opened top-level folders. We look two levels deep, and identify a dart project by looking for a pubspec.yaml file or a .packages file.

**Comment by devoncarew** [comment]
What might possibly help here is to decorate dart projects in the tree view. That would give the user an indication that we had successfully identified their dart projects.

**Comment by zanderso** [comment]
Sure. My project folder is //src, and the Dart package is at //src/mojo/dart/mojom.

**Comment by zanderso** [comment]
I mean, understanding this now, I could make sure I have a project directory for each dart package I'm working on, so this might be an education thing more than anything else.

**Comment by DanielJoyce** [comment]
Yeah, if you have multiple dart sub projects under a git repo, the editor gets confused sometimes. 

How do you create a project directory

**Comment by devoncarew** [comment]
Closing; we have a separate issue for decorate items in the tree view.
