### ISSUE TITLE
Dart SDK alert

### ISSUE THREAD

**Issue by darkn3rd** [dart-atom/dartlang#1108]
I just want to view the code I wrote before with color syntax highlighting, so I was looking for a `language-dart`, but a message says this is deprecated and to use `dartlang`, which does a lot more than just color syntax highlighting.

Anyway to get just the color syntax highlighting and shut other stuff off?

**Comment by devoncarew** [comment]
> Any way to get just the color syntax highlighting and shut other stuff off?

The plugin may work like that if you don't configure an SDK, but that's not really an intended use case for the plugin, so your mileage may vary...
