### ISSUE TITLE
Refactor rename dialog shows identifier twice

### ISSUE THREAD

**Issue by abarth** [dart-atom/dartlang#1114]
1. Open a Dart project.
2. Right click on an identifier and select "Rename..."

![screen shot 2017-01-31 at 10 05 09 pm](https://cloud.githubusercontent.com/assets/112007/22496789/a4c79162-e801-11e6-9006-df86e11c872a.png)

Notice that the identifier `root` appears twice in this dialog.  Only the second instance is editable, and the renaming works fine, the dialog just looks funky.

/cc @devoncarew

**Comment by cdavidjean** [comment]
Fixed in https://github.com/dart-atom/atom.dart/pull/51
