### ISSUE TITLE
The built-in library 'dart:html' is not available on the stand-alone VM.

### ISSUE THREAD

**Issue by nbro** [dart-atom/dartlang#1115]
I'm really new to Dart and, actually, I still need to learn the language. But I was setting up Atom as my developing environment to use this plug-in. A button "to run" appeared on a panel on top of the editor, so I clicked it, and I received the following error:

```
web/main.dart • ~/Desktop/tests/test2 • checked mode • debug
The built-in library 'dart:html' is not available on the stand-alone VM.
'file:///Users/cell/Desktop/tests/test2/web/main.dart': error: line 4 pos 1: library handler failed
import 'dart:html';
^
Unable to connect to the observatory (port 16199).
process finished • exit code 254
```

[Apparently this error occurs because I'm not developing on Dartium](http://stackoverflow.com/questions/34773326/running-dart-project-says-darthtml-is-not-available-for-the-standalone-vm), and `.dart` files can only run on Dartium. So I built first (on the terminal), using `pub build`, the project created using `stagehand`.

My question are: When is this "run" button really useful? Is there a way to build the project by clicking that button instead of doing what it actually does? 

Maybe it would be better first to learn the language and I would probably understand the differences here...

**Comment by devoncarew** [comment]
This plugin can't launch web projects, just CLI ones. The best workflow for using this plugin with web development is to edit in atom, run your server from the CLI, and open/refresh the app in dartium.

Thanks for the issue!
