### ISSUE TITLE
Missing outline

### ISSUE THREAD

**Issue by ThomasLocke** [dart-atom/dartlang#1117]
Atom 1.14.1 x64
Dartlang 0.6.45

I can't seem to turn the outline view on. Nothing happens. Everything else appears to be working just fine.

I'm not getting any errors on the console.

Is it broken in general, or is it just my Atom + Dartlang plugin that's not working?

**Comment by ThomasLocke** [comment]
Ah, I guess I'm getting hit by this: https://github.com/dart-atom/dartlang/commit/f076c5e3b51f1ba45680961ad63e60d3c4eb4561

Any plans for a fix, or am I just out of luck on this one?  :)

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-atom/dartlang/pull/1130
