### ISSUE TITLE
Lints no longer show up in IDE

### ISSUE THREAD

**Issue by jacehensley-wf** [dart-atom/dartlang#1118]
After upgrading to [Linter v2](http://steelbrain.me/2017/03/13/linter-v2-released.html) infos, warnings, and errors are not showing up in the IDE. They still show up in the warning panel.

![image](https://cloud.githubusercontent.com/assets/12398382/23971199/32b02346-098a-11e7-9964-cebd855d8ac9.png)

**Comment by devoncarew** [comment]
From looking over that blog post, it's likely that we have some API changes to deal with to work with the v2 of the linter -

**Comment by jacehensley-wf** [comment]
I'd be happy to help out if you point me in some general direction 😄

**Comment by devoncarew** [comment]
Great!

This file: https://github.com/dart-atom/dartlang/blob/master/lib/atom_linter.dart is our interface to the linter API. I suspect (but haven't checked) that this is where things may have broken.

We define our our UI for how to show lints (the errors view). It looks like the v2 linter has both a better UI than the v1 linter and a configurable one. So - a much more comprehensive bit of work - would probably involve removing our custom problems view. But just getting things back to working would be a good start :)
