### ISSUE TITLE
I miss a "problems view"

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#112]
If I have a project open, but no files open, then I don't see a way to get to the "project problems view".

![screen shot 2015-07-22 at 9 04 40 am](https://cloud.githubusercontent.com/assets/5479/8830423/f8d10f00-3050-11e5-8adf-9552568ea63b.png)

I'd love to see a list of issues/warnings/hints for the project, as a whole.

**Comment by radicaled** [comment]
We use `linter` to display issues/warnings/hints; it seems like they don't show the panel for project-wide linters if you don't have a file open, though. Feature request / bug report?

https://github.com/atom-community/linter/

**Comment by devoncarew** [comment]
https://github.com/dart-atom/dartlang/pull/260
