### ISSUE TITLE
Outline View no longer works

### ISSUE THREAD

**Issue by sgonyea** [dart-atom/dartlang#1122]
In the latest Atom, "Toggle Outline View" no longer shows an outline view.

**Comment by sgonyea** [comment]
Uh oh. It looks like alt-enter to add missing imports isn't working either?

**Comment by ThomasLocke** [comment]
Confirmed also with Slackware 14.2 x64 and atom 1.17.2

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-atom/dartlang/pull/1130
