### ISSUE TITLE
Installing packages Failed

### ISSUE THREAD

**Issue by sandrobilbeisi** [dart-atom/dartlang#1125]
The latest update of the plugin locked up the editor in read-only mode,
so I uninstalled Atom and all of its preferences and support files and reinstalled it all from scratch ...

now it gives a package installation error, even though those commands ( such as pub get ) work manually just fine
![screen shot 2017-05-28 at 15 37 44](https://cloud.githubusercontent.com/assets/755824/26529183/aa12ff1a-43bb-11e7-917f-a8a009013437.png)

**Comment by ThomasLocke** [comment]
I also get this on Slackware 14.2 x64.

As soon as I install the dartlang package on atom 1.17.2, those two popups appear on startup.

**Comment by parkerd** [comment]
See #1126 for how you can fix this until the package is updated.
