### ISSUE TITLE
NullError: method not found: 'apply' on null

### ISSUE THREAD

**Issue by apapasterg** [dart-atom/dartlang#1126]
Atom 1.17.2, dartlang 0.6.46, SDK 1.23.0 running on linux.
![atom-dartlang](https://user-images.githubusercontent.com/3769018/26941222-5ce97a2e-4c86-11e7-883d-0ab23aa85fa6.png)

**Comment by parkerd** [comment]
This appears to be because synced-sidebar has been removed from apm, but is still listed as a dependency here: https://github.com/dart-atom/dartlang/blob/master/package.json#L22

Manually removing that line from `~/.apm/packages/dartlang/package.json` fixes the error for me.

**Comment by devoncarew** [comment]
Thanks for the pointer! Published a new version w/o the dep.

**Comment by adrian83** [comment]
After removing ~/.atom directory and reinstalling atom the problem still occurs. My package.json doesn't contain any 'synced-sidebar' entries.

**Comment by faku99** [comment]
@adrian83 I fixed this issue by installing [atom-toolbar](https://atom.io/packages/atom-toolbar).

**Comment by adrian83** [comment]
Works for me. Thanks
