### ISSUE TITLE
Jumping to definition highlights incorrect text, but lands in approx right place

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#116]
![screen shot 2015-07-23 at 3 02 22 pm](https://cloud.githubusercontent.com/assets/5479/8863260/f7810a32-314b-11e5-9eec-4f375b14c72a.png)

From another file, I right-clicked on `Library` and selected the jump to definition. I'm taken to the location in the screenshot. Correct line, it appears, but look at the incorrect text highlighting.

**Comment by sethladd** [comment]
Maybe an analysis server issue?  I'm reproing it right now, if there's debug information I could collect that would be useful.

cc @bwilkerson

**Comment by sethladd** [comment]
Here's another case where it gets confused:

![screen shot 2015-07-23 at 3 17 29 pm](https://cloud.githubusercontent.com/assets/5479/8863484/faff6a3a-314d-11e5-96a7-de05f36baf65.png)

**Comment by sethladd** [comment]
@johnmccutchan has seen something similar, IIR

**Comment by johnmccutchan** [comment]
Yep, happens all the time.

**Comment by devoncarew** [comment]
If you guys notice a pattern or can find a reproducible case, please let me know. It'll help me reduce the time to identify what's causing it.

**Comment by sethladd** [comment]
I haven't noticed a pattern, unfortunately. I think we need some sort of way to send detailed logs and state info when we notice the AS falls off the rails. Maybe capture a log of traffic from the AS that we can send over? Is there a log of exceptions from the AS?

**Comment by radicaled** [comment]
If you set the 'logging' preference (only available in dev mode) to 'finer' you'll be able to see all logs in the console.

**Comment by devoncarew** [comment]
Possibly related? https://github.com/dart-lang/sdk/issues/23919

**Comment by devoncarew** [comment]
@bwilkerson, I have been able to work up a repro case for this. The offsets returned are correct. The line/col values are not in some circumstances. On a fresh analysis, it seems like the line/col values are correct. After an edit however (delete overlay / add overlay) the line/col can be incorrect. Subsequent edits might then cause the values to become correct. I'll demo this in person.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1262453007

**Comment by devoncarew** [comment]
This is fixed in the latest dart dev sdk release (`1.12.0-dev.5.0`).
