### ISSUE TITLE
Reanalyzing if analysis server was shutdown will generate a red error

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#117]
Shutdown the analysis service.
Then, select "Reanalyze sources" from the Packages | Dart menu.

I get this error:

![screen shot 2015-07-23 at 4 39 20 pm](https://cloud.githubusercontent.com/assets/5479/8864667/8bc5600a-3159-11e5-862c-f1bd292d3cb6.png)

**Comment by radicaled** [comment]
Fixed by #119.

**Comment by sethladd** [comment]
Thanks!
