### ISSUE TITLE
Code completing in an import statement isn't correct

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#123]
For example:

![screen shot 2015-07-28 at 10 09 19 am](https://cloud.githubusercontent.com/assets/5479/8938017/c71ef67e-3510-11e5-9cb0-f23a47d9b085.png)

Expected: while typing a path in an import statement, I'd like to see valid paths, not package: as an option.

Thanks for taking a look!

**Comment by devoncarew** [comment]
fixed by https://github.com/dart-atom/dartlang/pull/170
