### ISSUE TITLE
Warnings for missing methods from superclass could include more info

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#131]
![screen shot 2015-07-29 at 3 56 50 pm](https://cloud.githubusercontent.com/assets/5479/8971971/7e0808c2-360a-11e5-8bb6-3b20e1bd9d63.png)

Notice how it says "missing concrete implementation of setter 'List.length'". It would be nice if it showed the signature for `length`.

Better yet, it would be great if there was a quick fix that just added in those method. :)

**Comment by devoncarew** [comment]
@lukechurch

@sethladd - thanks for the report. I believe the resolution for this would be in the analysis engine.

**Comment by sethladd** [comment]
Ah, that message comes straight from the analysis server? OK, I'll move the issue.

**Comment by sethladd** [comment]
Moved!
