### ISSUE TITLE
More real-time feedback when SDK dir is correct?

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#138]
Consider this case:

* Change your SDK location in the package's settings
* We see a nice blue pop-up (no sdk detected)... yay!
* Change your SDK location again, and take focus away from that field

Actual: no persistent signal that the SDK is not configured

Expected: some persistent signal (a red X ?) that the SDK is not configured, and a persistent signal (a green check?) when it is configured.

Notice from this screenshot that there's no good/bad signal about my SDK:

![screen shot 2015-07-30 at 3 41 45 pm](https://cloud.githubusercontent.com/assets/5479/8996995/86ec7636-36d1-11e5-821b-694b3e18422e.png)

Thanks for the consideration!

**Comment by devoncarew** [comment]
I don't believe the setting page is that configurable. I think the limit of the validation we can do is type the fields (int, bool, ...) or set up enums for some settings. Anything dynamic would need to really hack the dom, or we'd need to contribute some extendability to the settings page itself.

We could show the sdk status elsewhere in the UI. We have the status-bar, and potentially the toolbar. One thing to keep in mind is that the user may not be doing dart development all the time. They may have installed the plugin, but might not want to see persistent warnings about it.

Perhaps we show some UI, if we think they're working on a dart project, and there's no sdk configured.

**Comment by sethladd** [comment]
I'd only want to see a persistent YES/NO on the Dart package settings page. Maybe we can ask the Atom devs for more control here.

**Comment by rmacnak-google** [comment]
I did get a green pop-up after entering a correct sdk, so presumably it could do a red one after entering an incorrect sdk, or whenever it tries to use the sdk and can't find it.

**Comment by sethladd** [comment]
From the wild: we just worked with a user that had an incorrect SDK path. There wasn't a visual indication that the SDK path was incorrect.
