### ISSUE TITLE
How to hide the linter output at bottom of editor tab?

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#141]
Having trouble figuring out how to hide the list of hints/warnings/etc.

Thanks!

**Comment by devoncarew** [comment]
There's an option for it in the `linter` plugin.

<img width="251" alt="screen shot 2015-07-31 at 2 07 44 pm" src="https://cloud.githubusercontent.com/assets/1269969/9017776/8b5965be-378d-11e5-91da-f8d6391aace5.png">

**Comment by sethladd** [comment]
Thanks!  "The more I know" :)
