### ISSUE TITLE
No autocomplete on some aliased libraries

### ISSUE THREAD

**Issue by alechenninger** [dart-atom/dartlang#142]
Not sure if this is just a missing feature in the analyzer.

Ctrl+space after library definition, no suggestions appear:
![screenshot from 2015-07-31 13-53-05](https://cloud.githubusercontent.com/assets/3496559/9013707/9bb8778a-378b-11e5-8e47-f215a3479a61.png)

However, if I remove the `as shelf`, ctrl+space on an empty newline includes suggestions from the shelf library as expected (such as `createMiddleware`):
![screenshot from 2015-07-31 13-55-38](https://cloud.githubusercontent.com/assets/3496559/9013767/0d76b5bc-378c-11e5-9398-fcdf5b2bf38d.png)

**Comment by devoncarew** [comment]
I'm not seeing this behavior. What version of the sdk / analysis server are you running? I'm on the latest dev sdk (`1.12.0-dev.4.0`) - AS 1.9.0.

You can find the AS version using the `analysis server status` atom command.

@danrubel

**Comment by alechenninger** [comment]
Dart VM version: 1.12.0-dev.4.0 (Tue Jul 21 03:52:32 2015) on "linux_x64"
Analysis server 1.9.0

I get mixed results too, actually. On one project it works fine.

If you use stagehand and create a shelf server (`stagehand server-shelf`), this project seems to consistent reproduce the issue. Interestingly though, only on the "shelf" alias... the "io" alias works fine. (!?)

**Comment by radicaled** [comment]
Does autocompletion work if you run `pub get` and wait a few seconds?

**Comment by alechenninger** [comment]
Unfortunately, no. I also tried renaming the alias a few different things, removing it, putting it back. No change.

**Comment by devoncarew** [comment]
@alechenninger, can you see if the new version (`0.3.11`) fixes this?

**Comment by alechenninger** [comment]
Still seeing the same behavior

**Comment by alechenninger** [comment]
Woohoo, this is working with the latest version of the dev sdk (1.12.0-dev.5.0)

**Comment by devoncarew** [comment]
Good enough! Thanks for re-testing.
