### ISSUE TITLE
Sort autocomplete suggestions by applicable types

### ISSUE THREAD

**Issue by alechenninger** [dart-atom/dartlang#143]
The first results should be types which are most relevant to the current assignment.

For example, if I'm passing an argument which annotated with type `Foo` to a function, and I type `new ` + ctrl+space, I should first see suggestions for constructors of types which will implement `Foo`.

**Comment by devoncarew** [comment]
Hi @alechenninger, can you re-file this at https://github.com/dart-lang/sdk? Thanks!

**Comment by alechenninger** [comment]
Gladly, cheers
