### ISSUE TITLE
renaming a field doesn't work

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#149]
"validator can only be passed if treeSanitizer is null"

In case it's relevant, here's the Dart version I'm using.

dart --version
Dart VM version: 1.11.0 (Wed Jun 24 06:34:37 2015) on "macos_ia32"

References
4 results found.
miniml lib/src/tokenizer.dart
22: int _scanStart = 0;
45: _finishedStart = _scanStart;
85: ….string.substring(_scanStart, _here);
48: _scanStart = _here;
Uncaught Uncaught Error: Invalid argument(s): validator can only be passed if treeSanitizer is null Stack Trace: Invalid argument(s): validator can only be passed if treeSanitizer is null at [object Object].dart.wrapException (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:15041:17) at DivElement. (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:30081:19) at DivElement.dart.Element.setInnerHtml$3$treeSanitizer$validator (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:30120:35) at [object Object].J.setInnerHtml$3$treeSanitizer$validator$x (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:35946:41) at [object Object].dart.promptUser (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:19027:9) at RefactoringHelperhandleRenameRefactor_closure.dart.RefactoringHelperhandleRenameRefactor_closure.call$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:21514:18) at _RootZone.dart._RootZone.runUnary$2 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26957:20) at _FuturepropagateToListeners_handleValueCallback.dart._FuturepropagateToListeners_handleValueCallback.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:25116:80) at [object Object].dart._Future.static._FuturepropagateToListeners (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:25023:143) at _Future.dart._Future._completeWithValue$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:24903:11) at _FutureasyncComplete_closure0.dart._Future__asyncComplete_closure0.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:25102:38) at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:25244:30) at [object Object].dart._microtaskLoop (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:23955:12) at [object Object].dart._microtaskLoopEntry (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:23961:11) at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:14474:35) at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:16126:41) at _IsolateContext.dart._IsolateContext.eval$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:14090:25) at [object Object].dart._callInIsolate (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:13721:28) at dart.invokeClosure (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:15189:18) at /Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:15210:18

**Comment by devoncarew** [comment]
Fixed.

**Comment by skybrian** [comment]
Thanks!
