### ISSUE TITLE
null pointer navigating to declaration

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#150]
I was testing whether "Go to declaration" would work for a reference in a doc comment, and somehow got this stack trace. It's not reproducible, though.

Uncaught Uncaught Error: NullError: method not found: 'split$1' on null Stack Trace: TypeError: Cannot read property 'split$1' of null at [object Object].J.split$1$s (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:36614:40) at _MatchParser.dart._MatchParser.parseMatch$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:22227:26) at FindReferencesView.dart.FindReferencesView._references$_render$2 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:22117:36) at [object Object]. (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:15523:32) at ListTreeBuilder.dart.ListTreeBuilder.render$2 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:20392:28) at ListTreeBuilder.dart.ListTreeBuilder._addNode$2 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:20312:16) at ListTreeBuilder.dart.ListTreeBuilder._addNode$2 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:20356:18) at ListTreeBuilder.dart.ListTreeBuilder.addNode$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:20303:21) at FindReferencesViewshowView_closure.dart.FindReferencesViewshowView_closure.call$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:22209:26) at _RootZone.dart._RootZone.runUnary$2 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:27405:20) at _FuturepropagateToListeners_handleValueCallback.dart._FuturepropagateToListeners_handleValueCallback.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:25564:80) at [object Object].dart._Future.static._FuturepropagateToListeners (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:25471:143) at _Future.dart._Future._complete$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:25345:13) at Stream_toList_closure0.dart.Stream_toList_closure0.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26006:33) at _RootZone.dart._RootZone.runGuarded$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:27339:20) at _BufferingStreamSubscriptionsendDone_sendDone.dart._BufferingStreamSubscription__sendDone_sendDone.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26622:18) at _ControllerSubscription.dart._BufferingStreamSubscription._sendDone$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26530:14) at _DelayedDone.dart._DelayedDone.perform$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26706:18) at _StreamImplEvents.dart._StreamImplEvents.handleNext$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26767:16) at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26742:12) at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:25692:30) at [object Object].dart._microtaskLoop (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:24403:12) at [object Object].dart._microtaskLoopEntry (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:24409:11) at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:14702:35) at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:16354:41) at _IsolateContext.dart._IsolateContext.eval$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:14318:25) at [object Object].dart._callInIsolate (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:13949:28) at dart.invokeClosure (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:15417:18) at /Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:15438:18

**Comment by skybrian** [comment]
I also noticed that "go to declaration" in the same file highlights the wrong thing if I've edited it. Running "Re-analyze sources" fixed it.

**Comment by devoncarew** [comment]
Re: the incorrect highlighting offsets - that'll be fixed in the next dev sdk release of the analysis server. There are some bugs tracking it in this repo that I'll close out once the next dev sdk is available.

**Comment by devoncarew** [comment]
For the NPE, any chance that it was for a file that wasn't saved to disk, had no disk representation, or may have had a read error?

**Comment by skybrian** [comment]
I don't think so, but I think I edited the file at almost the same time.

There is an odd delay before showing stack traces. I'll start an action, then nothing happens, so I'll run it again (or think about it) and then see the error. So perhaps I'm introducing race conditions somehow?

**Comment by devoncarew** [comment]
> There is an odd delay before showing stack traces.

The atom exception reporting box? Their code searches the plugin's github repo for duplicate issues so you don't get n reports for the same exception. The query takes a few seconds to return -
