### ISSUE TITLE
RangeError finding references after editing a file

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#152]
Also in MatchParser.

Uncaught Uncaught Error: RangeError: Value not in range: 16 Stack Trace: RangeError: Value not in range: 16 at [object Object].dart.wrapException (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:15269:17) at JSString.dart.JSString.substring$2 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:13728:19) at _MatchParser.dart._MatchParser.parseMatch$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:22239:20) at FindReferencesView.dart.FindReferencesView._references$_render$2 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:22117:36) at [object Object]. (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:15523:32) at ListTreeBuilder.dart.ListTreeBuilder.render$2 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:20392:28) at ListTreeBuilder.dart.ListTreeBuilder._addNode$2 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:20312:16) at ListTreeBuilder.dart.ListTreeBuilder._addNode$2 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:20356:18) at ListTreeBuilder.dart.ListTreeBuilder.addNode$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:20303:21) at FindReferencesViewshowView_closure.dart.FindReferencesViewshowView_closure.call$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:22209:26) at _RootZone.dart._RootZone.runUnary$2 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:27405:20) at _FuturepropagateToListeners_handleValueCallback.dart._FuturepropagateToListeners_handleValueCallback.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:25564:80) at [object Object].dart._Future.static._FuturepropagateToListeners (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:25471:143) at _Future.dart._Future._complete$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:25345:13) at Stream_toList_closure0.dart.Stream_toList_closure0.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26006:33) at _RootZone.dart._RootZone.runGuarded$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:27339:20) at _BufferingStreamSubscriptionsendDone_sendDone.dart._BufferingStreamSubscription__sendDone_sendDone.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26622:18) at _ControllerSubscription.dart._BufferingStreamSubscription._sendDone$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26530:14) at _DelayedDone.dart._DelayedDone.perform$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26706:18) at _StreamImplEvents.dart._StreamImplEvents.handleNext$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26767:16) at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:26742:12) at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:25692:30) at [object Object].dart._microtaskLoop (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:24403:12) at [object Object].dart._microtaskLoopEntry (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:24409:11) at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:14702:35) at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:16354:41) at _IsolateContext.dart._IsolateContext.eval$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:14318:25) at [object Object].dart._callInIsolate (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:13949:28) at dart.invokeClosure (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:15417:18) at /Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:15438:18

**Comment by sethladd** [comment]
Thanks for the report!
