### ISSUE TITLE
code generator has deoptimised the styling warning during install.

### ISSUE THREAD

**Issue by eseidel** [dart-atom/dartlang#156]
I can't imagine this matters, but figured you should know.

```
% apm install linter dartlang
Installing linter to /Users/eseidel/.atom/packages ✓
Installing dartlang to /Users/eseidel/.atom/packages 
[BABEL] Note: The code generator has deoptimised the styling of "/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js" as it exceeds the max of "100KB".
✓
```

http://stackoverflow.com/questions/29576341/what-does-the-code-generator-has-deoptimised-the-styling-of-some-file-as-it-e

**Comment by devoncarew** [comment]
Thanks for the heads up! I wasn't aware of this warning message. Looks like other compile-to-JS languages have run into this: http://stackoverflow.com/questions/31197141/babel-error-when-installing-atom-and-atom-typescript-package.

I'll close this out as I don't think it affects us.
