### ISSUE TITLE
Fails to autocomplete dart: package names 

### ISSUE THREAD

**Issue by eseidel** [dart-atom/dartlang#159]
dartlang offers to autocomplete packages, but if you type past the colon ':' it fails to.

Example:
![screen shot 2015-08-02 at 10 19 48 am](https://cloud.githubusercontent.com/assets/478541/9027189/2e02ab40-3900-11e5-8d19-9f8cd7f60ac8.png)
![screen shot 2015-08-02 at 10 19 58 am](https://cloud.githubusercontent.com/assets/478541/9027190/30dce0f6-3900-11e5-9cbe-3c7922b8f236.png)

**Comment by eseidel** [comment]
I would expect it to winnow the search down to just package names that start with 'i' and tab to then complete to dart:io, possibly including even the trailing ' and ;

**Comment by devoncarew** [comment]
Possibly related to https://github.com/dart-atom/dartlang/issues/123. Looks like there are a few code completion issues in import statements. @danrubel

I'll see if the issues are on the atom plugin side or the analysis server side -

**Comment by danrubel** [comment]
This seems to work in the Dart Plugins for Eclipse. Let me know if this turns out to be a server issue.

**Comment by sethladd** [comment]
Seems to work OK in WebStorm:

![screen shot 2015-08-03 at 12 36 30 pm](https://cloud.githubusercontent.com/assets/5479/9045954/4bcb4696-39dc-11e5-9e71-f2bfc87b836c.png)

(it doesn't put the quote and the ; at the end, but it does find the right options for `dart:i`)

**Comment by devoncarew** [comment]
Fixed by https://github.com/dart-atom/dartlang/pull/170
