### ISSUE TITLE
dart: autocompletes insert the wrong content

### ISSUE THREAD

**Issue by eseidel** [dart-atom/dartlang#160]
If you select from the dropdown when doing a dart: autocomplete, it pastes the whole name of the package.

![screen shot 2015-08-02 at 10 22 53 am](https://cloud.githubusercontent.com/assets/478541/9027200/907ab81c-3900-11e5-8ac3-3e7ff15e7a4f.png)

![screen shot 2015-08-02 at 10 22 59 am](https://cloud.githubusercontent.com/assets/478541/9027202/941f94d8-3900-11e5-9d88-1ae477ed6d67.png)

I would instead expect it to complete the import 'dart:convert' adding at least the trailing ' as well as probably the trailing ; and probably putting my cursor on the next line.

**Comment by alechenninger** [comment]
Found a similar kind of thing happens with autocompleted paths in `part` declarations

**Comment by devoncarew** [comment]
Fixed by https://github.com/dart-atom/dartlang/pull/170
