### ISSUE TITLE
Explain how to invoke dartfmt.

### ISSUE THREAD

**Issue by zanderso** [dart-atom/dartlang#163]
This was hard for me to discover. I only noticed in the changelog that this was possible from a context menu. Maybe there should be a Function key binding, but either way it might be a good idea to document in README.md and/or the plug-in Settings page.

**Comment by radicaled** [comment]
Pretty much anything and everything in Atom is available via the Command Palette: CTRL+P on Windows and Linux, and CMD+P on OS X. The Command Palette will also show you the key combos available to quickly invoke the desired command, if available.

**Comment by zanderso** [comment]
Be that as it may, I'd still recommend explaining in the Dart plugin README.md how to invoke the standard set of Dart tools. Dart coding will be the first time many people are using Atom.

**Comment by devoncarew** [comment]
Yeah, I think we need a quick, 5-min getting started guide. It'll help make people familiar w/ the features that are available. Part of that doc will be to help get people familiar w/ how things work in atom in general.

**Comment by sethladd** [comment]
I'll add a quick note to the README.

**Comment by sethladd** [comment]
Added https://github.com/dart-atom/dartlang/commit/6e98ad1dc3b20d0df46420eaa35a829d16131ac1
