### ISSUE TITLE
How to search for a Dart name across the entire Dart project?

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#172]
I'd like to find a string (lexically, or better yet: semantically) across my code and all packages referenced by my code.

Cmd-Shift-F doesn't seem to search into packages.

Thanks!

**Comment by sethladd** [comment]
I'm really missing this functionality. Trying to learn Flutter, and there a ton of new APIs and class names. I'd love to be able to search for "OneChildRenderObjectWidget" and find the file that the class is defined in.

**Comment by devoncarew** [comment]
I used the find type dialog very heavily in Eclipse - one of the four or five features I used most.

**Comment by a14n** [comment]
+1

**Comment by devoncarew** [comment]
Closing in favor of #151.
