### ISSUE TITLE
Code completion a path in an import shows dart: libraries

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#173]
![screen shot 2015-08-03 at 9 27 19 pm](https://cloud.githubusercontent.com/assets/5479/9053205/867994d8-3a26-11e5-9732-53b9acd5602d.png)

Was expecting to see file options that work, given the beginning of the path.

**Comment by devoncarew** [comment]
fixed

**Comment by sethladd** [comment]
Thanks!
