### ISSUE TITLE
Do not code completing in text in a comment

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#175]
![screen shot 2015-08-04 at 7 59 23 am](https://cloud.githubusercontent.com/assets/5479/9063914/c5021600-3a7e-11e5-909a-6bc49d7d5f47.png)

When I'm writing a comment, I probably don't want code completion.

I do want code completion inside of a doc reference, though.

**Comment by sethladd** [comment]
This might be controversial.

**Comment by devoncarew** [comment]
We don't use the dart completer in comments. Atom falls back to the built-in lexical completer. We can choose to:
- use the dart completer and see what happens
- continue with the lexical one
- have no completions in comments (remove both completers)
