### ISSUE TITLE
Make obvious/easy that quick fixes exist for warnings?

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#177]
Hi,

From https://github.com/dart-lang/sdk/issues/23965 I'm wondering if we can make it more obvious that a quick fix(es) exist for a warning we might see in the linter's output.

It would be really nice to see a warning, notice that there's a fix, and click/select/activate that fix. Boom. Warning disappears. :)

Thanks!

**Comment by devoncarew** [comment]
This is blocked on https://github.com/dart-lang/sdk/issues/23874.

**Comment by devoncarew** [comment]
Closing as a dup of https://github.com/dart-atom/dartlang/issues/89. If you can push on https://github.com/dart-lang/sdk/issues/23874, that would be great.
