### ISSUE TITLE
spacing in warning issue

### ISSUE THREAD

**Issue by kasperpeulen** [dart-atom/dartlang#178]
Really amazed by the quality of this plugin already @devoncarew awesome

Very tiny nit, but I feel like there could maybe be some spacing between 'CommandRunner' and 'at line..' 

see the picture:

![image](https://cloud.githubusercontent.com/assets/1035299/9067115/e37b1660-3adb-11e5-8ee8-8756ec0c2265.png)

**Comment by devoncarew** [comment]
I think this has to do with the theme that you're using in atom:

<img width="433" alt="screen shot 2015-08-04 at 10 18 40 am" src="https://cloud.githubusercontent.com/assets/1269969/9067476/8bff4ea4-3a92-11e5-9074-d52cb996a2a9.png">

That said, the `linter` project is very open to contributions :) We've pushed in a few UI related ones as we've needed them.

**Comment by devoncarew** [comment]
Thanks for the feedback @kasperpeulen! I'm closing this issue as it's a problem from the underlying https://github.com/atom-community/linter plugin.

**Comment by kasperpeulen** [comment]
Sure :)
Op 8 aug. 2015 22:17 schreef "Devon Carew" <notifications@github.com>:
