### ISSUE TITLE
New syntax: null-aware operators

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#18]
Hi!

New syntax is coming in 1.12. Here's some samples:

```
print(exp ?? other); // prints other if exp is null

obj ??= 'hi';  // sets obj to hi if obj is null

obj?.method(); // calls method if obj is not null
```

The 1.12-dev SDK supports this now, if you want to try it out.

Hope that helps!

**Comment by devoncarew** [comment]
How they're highlighted currently:

<img width="357" alt="null" src="https://cloud.githubusercontent.com/assets/1269969/8764923/8819a686-2da9-11e5-9231-d163f1cce27f.PNG">

**Comment by devoncarew** [comment]
https://github.com/dart-lang/sdk/issues/23863

**Comment by devoncarew** [comment]
updated:
<img width="332" alt="null" src="https://cloud.githubusercontent.com/assets/1269969/8764961/a08cefaa-2dab-11e5-9edd-851d7a93ed83.PNG">

**Comment by devoncarew** [comment]
We turn in on in the analysis server, and highlight the null-aware operators now.
