### ISSUE TITLE
Named parameters for constructors should have autocomplete suggestions

### ISSUE THREAD

**Issue by abarth** [dart-atom/dartlang#186]
We use a lot of named parameters in Sky.  It would be nice if the dartlang would suggest the names of the named parameters so we don't have to memorize them.

**Comment by devoncarew** [comment]
@danrubel, is there an issue tracking this in the sdk repo?

**Comment by danrubel** [comment]
Should already be in there. After the last required param, if you put a comma then ctrl-space, you should receive a list of named param suggestions in amongst all the other suggestions. If this is not the case, please let me know and I'll dig.

**Comment by abarth** [comment]
Maybe it doesn't work for named arguments to constructors?  For example,

import 'package:sky/widgets.dart';

new EdgeDims.symmetric(

ctrl-space doesn't show the named arguments.

**Comment by abarth** [comment]
It does seem to work for functions but not constructors.

**Comment by devoncarew** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/24004.

**Comment by devoncarew** [comment]
The AS issues has been fixed; this will be available in the next dev SDK (~2 weeks).
