### ISSUE TITLE
Syntax not highlighted as expected (in chain of methods)

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#193]
![screen shot 2015-08-07 at 12 54 06 pm](https://cloud.githubusercontent.com/assets/5479/9144700/734db01c-3d03-11e5-83a6-165694abd6ed.png)

Expected: toList and sort to be higlighted.

Here's an example where it works:

![screen shot 2015-08-07 at 12 54 55 pm](https://cloud.githubusercontent.com/assets/5479/9144707/841987ae-3d03-11e5-9bd7-aaa263535a6a.png)

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-atom/dartlang/commit/cfdacadefa6dc316e4d40edd285df70a39ee7d23

<img width="611" alt="screen shot 2015-08-15 at 7 44 01 pm" src="https://cloud.githubusercontent.com/assets/1269969/9291944/34dcec7c-4392-11e5-9aca-3ae91588aa42.png">

**Comment by sethladd** [comment]
Excellent!
