### ISSUE TITLE
deleting a file does not remove errors/warnings associated with the file

### ISSUE THREAD

**Issue by keertip** [dart-atom/dartlang#194]
If I delete a dart file in the project, the problems associated with the file are still shown, and selecting them opens an empty file.

**Comment by radicaled** [comment]
Unable to reproduce on latest stable. Dart version? Any repo steps beyond deleting a dart file with errors?

**Comment by devoncarew** [comment]
@keertip, is this with a file, a directory, or a full dart project?

**Comment by keertip** [comment]
Not able to reproduce this. Maybe the analysis server was not alive at that point and I had not noticed that? Closing issue.
