### ISSUE TITLE
publish to https://atom.io/packages

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#2]
Is there anything we want to get done before we publish?

**Comment by sethladd** [comment]
Our repo is renamed. Please publish to atom.io ASAP.

Thanks!

**Comment by devoncarew** [comment]
Let's rename to dartlang first :)

**Comment by devoncarew** [comment]
blocked on #3

**Comment by sethladd** [comment]
@devoncarew @radicaled what are the blocking issues here?

I'll upload to Atom when we're in a min-viable state.

**Comment by sethladd** [comment]
Done!
