### ISSUE TITLE
Are "TODOs" really "Issues" ?

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#200]
Create a new stagehand package-simple.
Run pub get.
Open Atom for that new package.

Notice how there is one red Issue. Scary! Click it, and you're taken to a TODO. Not so scary.

How much control do we have over what's an "Scary Red Issue" ?

![screen shot 2015-08-10 at 8 58 11 am](https://cloud.githubusercontent.com/assets/5479/9176105/333bd444-3f3e-11e5-964d-aafd0b71db42.png)

**Comment by alechenninger** [comment]
Personally, I feel this should be scoped beyond just TODO's, and also include other non-show-stopping issues like deprecation warnings and unused imports/variables.

**Comment by devoncarew** [comment]
Partly addressed here: https://github.com/dart-atom/dartlang/pull/260. Will probably need to submit PRs to `linter` fix fix the scary red issue.
