### ISSUE TITLE
Option to default to --no-package-symlinks

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#203]
Pub doesn't have a way to globally set this flag (as far as I know?).

Since Atom runs pub on behalf of the user, can we provide an option to either pass flags to pub or set that --no-package-symlinks ?

Thanks!

**Comment by sethladd** [comment]
For tracking: https://github.com/dart-lang/pub/issues/1311

**Comment by devoncarew** [comment]
Just to run down the implementation:

- add a new pref to lib/plugin.dart
- when running pub commands (lib/impl/pub.dart) check to see if that pref is set add pass in the symlinks flag

We possibly need to ensure that the current stable sdk won't choke on the flag? And if it will, don't pass it into the sdk depending on the version.

**Comment by sethladd** [comment]
> We possibly need to ensure that the current stable sdk won't choke on the flag? 

Good catch!

What if we just had a pref called "Options for pub" (name pending review)... this way, the user can put whatever they want in there. We don't need to check compatibility.

**Comment by sethladd** [comment]
Related: eclipse plugin got this option: https://github.com/dart-lang/eclipse3/pull/74

**Comment by devoncarew** [comment]
Cool. This option is currently mutually exclusive with running Sky apps. We should delay implementing this a bit, or add a disclaimer in the description for the preference setting.

**Comment by sethladd** [comment]
> This option is currently mutually exclusive with running Sky apps

Not entirely. Unless Sky apps *require* a packages/ dir?

**Comment by devoncarew** [comment]
Currently they do to run. The execution tool lives in
packages/sky/sky_tool. Medium term plans to change that. Will commit a cl
with a disclaimer in the prefs page.
