### ISSUE TITLE
Enter key long pause

### ISSUE THREAD

**Issue by johnmccutchan** [dart-atom/dartlang#210]
As discussed in person, the enter key in Atom with the dartplugin pauses typing for multiple seconds.
Overriding the key binding fixes the problem.

$ cd dart/sdk/runtime/observatory
$ atom .

1) Open lib/src/elements/debugger.dart

**Comment by devoncarew** [comment]
John, what other atom plugins do you have installed? We have run into issues w/ regexs in other plugins slowing us down in some cases. haml comes to mind.

**Comment by johnmccutchan** [comment]
@devoncarew I just went package by package and emmet was the problem.
