### ISSUE TITLE
Plugin consumes CMD+1 blocking tab switching

### ISSUE THREAD

**Issue by johnmccutchan** [dart-atom/dartlang#214]
In Atom, you switch between tabs with CMD+1, ..., CMD+9. The Dart plugin consumes CMD+1 (but not CMD+2, ..., CMD+9).

Reproduction:
1) Open the following file types in tabs: html file, dart file, html file
2) Go to tab 1
3) CMD+3 - switched to tab 3
4) CMD+1 - switched back tab 1
5) CMD+2 - switch to tab 2
6) CMD+1 - *ding noise*
7) CMD+3 - switch to tab 3

This is a very confusing.

**Comment by devoncarew** [comment]
Yup, open to ideas here. cmd-1 is a familiar quick-fix keystroke from other IDEs.

**Comment by devoncarew** [comment]
As a data point, IntelliJ uses alt-enter for the quick fix keybinding.

**Comment by johnmccutchan** [comment]
https://github.com/dart-atom/dartlang/pull/222

I do not think we should be using other IDEs as inspiration for key bindings. A holistic approach that does not interfere with the default keybindings for Atom or the host OS is the right approach.

Another data point: I've never once used or wanted my editor to "quick fix" my code.

**Comment by devoncarew** [comment]
Familiarity with other IDEs - esp. where the similar capabilities do not yet exist in atom - is useful. That said, we should avoid conflicting with existing bindings in atom in general.

**Comment by kasperpeulen** [comment]
> Another data point: I've never once used or wanted my editor to "quick fix" my code.

Another data point: I use quick fix on average 13 times per working day (according to my webstorm statistics).

> Familiarity with other IDEs - esp. where the similar capabilities do not yet exist in atom - is useful.

Agree with this. I would think alt+enter would be a good one, if it doesn't interfere with atoms key bindings.

**Comment by johnmccutchan** [comment]
Striving for familiarity can and often does run contrary to being the best.
