### ISSUE TITLE
Option for on-demand or less intrusive code completion

### ISSUE THREAD

**Issue by yjbanov** [dart-atom/dartlang#221]
Currently code completion pops up automatically, which doesn't match my coding style. I prefer hitting CTRL + Space myself when I need to see suggestions. Today I'm finding myself reaching for ESC a lot to remove the unwanted popup. Given that all other major IDEs have this option (IntelliJ, Eclipse, etc) I must be far from the only one who has this preference. Please add support for on-demand code completion.

An alternative is to have an option to make the dialog less intrusive. Perhaps move suggestions to the bottom bar, similar to how compiler warnings are displayed.

**Comment by devoncarew** [comment]
There are a bunch of settings for this in the `autocomplete-plus` package. You can do things like disabling completions from displaying automatically and adjusting the delay before they show. I'm pretty sure you can find what you want there -

**Comment by yjbanov** [comment]
Indeed I can. I guess I need to learn how to use Atom :)
