### ISSUE TITLE
errors won't don't disappear from editor window after error is fixed

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#226]
I don't have a way to reproduce it, but here are the symptoms:

After I've been editing for a while, sometimes Atom gets into a state where, for a particular file, errors don't disappear after I've fixed them. It looks like the Analyzer has finished running and detected no errors because it says "File 0" at the bottom. If I introduce an error and remove it, the "File" counter at the bottom goes to non-zero and back again with a slight lag (as expected). But there are still bullet points at the beginning of lines where the errors used to be, and there are underlined identifiers for errors that are no longer present.

When in this state, closing the file and reopening it again doesn't make it go away. Closing the project and opening it again doesn't make it go away. Quitting out of atom and reopening it does reset it.

The problem seems to be associated with a single file. I tried reproducing it by copying the file and opening it, but it didn't reproduce.

It seems like some text and line markers on the editor document are getting leaked somehow?

**Comment by devoncarew** [comment]
Closing this as assumed stale. We've changed the way we handle file overlays since this was filed.
