### ISSUE TITLE
Linking to Privacy Policy and ToS

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#229]
In the README, please link to:

Terms | Privacy

privacy: http://www.google.com/intl/en/policies/privacy/

Terms can be a paragraph:

"The Dart plugin for Atom (the "Plugin") is an open-source project, contributed to by Google. By using the Plugin, you consent to be bound by Google's general Terms of Service and Google's general Privacy Policy."

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-atom/dartlang/commit/722157e790c866d090b6f732d90c9ec2f70ff17d
