### ISSUE TITLE
open file in dartium option in context menu?

### ISSUE THREAD

**Issue by kasperpeulen** [dart-atom/dartlang#233]
Coming form webstorm I kind of expect an option to open the file in dartium, if right click a file:
![image](https://cloud.githubusercontent.com/assets/1035299/9364531/15d479f8-46ad-11e5-96f1-a2e2679d97dd.png)

Not really sure if this is something that should be added to the atom plugin ?

**Comment by devoncarew** [comment]
We want to have a general launching framework for this plugin. That'll let people hit `run` on a file and have it figure out what to launch and how to launch it. We'll contribute an implementation for running Sky apps.

For running web apps, you'd need to spin up a web server first and then open a browser instance against that server. It's totally doable, but at least for now outside of the scope of what I'm looking at.

Thanks for the feedback!

**Comment by devoncarew** [comment]
I'm closing this in favor of https://github.com/dart-atom/dartlang/issues/585; they're essentially the same issue.
