### ISSUE TITLE
Tilde in SDK path isn't supported

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#236]
If a user uses an SDK path like `~/path/to/dart` then the plugin won't activate.

**Comment by sethladd** [comment]
So tilde's are supported in the input field? Cool!

**Comment by devoncarew** [comment]
Looks like no, from testing it. Also not env variables. But we do do a much better job of letting users know about failing to locate an sdk; hopefully the user will have better tools to diagnose the issue.

**Comment by sethladd** [comment]
Reopening as we might want to support tilde one day. Glad we have better messaging, though.

**Comment by danrubel** [comment]
Fixed... https://github.com/dart-atom/dartlang/commit/1de5949f2357385985591cfad05c175cd77e8642
