### ISSUE TITLE
auto-complete should be ordering results in a more useful order

### ISSUE THREAD

**Issue by pstjvn** [dart-atom/dartlang#243]
I have a class definition with 5+ fields and I am trying to instantiate it:

```dart
var a = new MyClass()..[ctrl+space]
```
However the first suggested completions are: 
```
false, new, null, true
```
It does not seem like I would ever need to auto-complete those. 

Then appear all the properties (own and inherited) in an alphabetical order.
I think it would be more useful to provide the fields and properties at the top as very few programmers forget the keywords of a language.

**Comment by devoncarew** [comment]
+1!

@danrubel

**Comment by devoncarew** [comment]
Moved to https://github.com/dart-lang/sdk/issues/24201.

**Comment by devoncarew** [comment]
Thanks for the feedback!
