### ISSUE TITLE
Auto-completion does not show list of parameters

### ISSUE THREAD

**Issue by pstjvn** [dart-atom/dartlang#244]
Example code:

```
var ctrl = new StreamController.broadcast([ctrl+space])
```
I would expect to see arguments list when I invoke auto-complete while between the parenthesis, instead I see completion for the resulting object (i.s. the stream controller).

**Comment by devoncarew** [comment]
What sdk version are you using? @danrubel, I think you fixed an issue very much like this one recently?

**Comment by pstjvn** [comment]
Latest stable, I.e. the last one available currently as stable is 1.11.3

**Comment by devoncarew** [comment]
Cool. the atom dart plugin will work much better with the latest dev. There have been several fixes into the analysis server for issues that only were surfaced when driven by the atom plugin.

**Comment by devoncarew** [comment]
Thanks for the report! Closing in favor of the sdk one: https://github.com/dart-lang/sdk/issues/24004.
