### ISSUE TITLE
Add ability to exclude directories from dart analyzer

### ISSUE THREAD

**Issue by DanielJoyce** [dart-atom/dartlang#245]
The analyzer likes to analyze generated directories, which yields tons of spurious errors in some cases. There should be a way on a per-project dir basis to tell it which dirs to ignore

**Comment by devoncarew** [comment]
You can! Create a .analysis_options file and add the directory to it. We plan to have some UI support for this in the future. It depends on being able to parse yaml files, modify them, and write back something substantially similar to the original file.

**Comment by devoncarew** [comment]
https://github.com/dart-lang/dartdoc/blob/master/.analysis_options

**Comment by DanielJoyce** [comment]
Tried finding this in the dart docs and saw it mentioned nowhere visible.

On Mon, Aug 24, 2015, 16:27 Devon Carew <notifications@github.com> wrote:

> https://github.com/dart-lang/dartdoc/blob/master/.analysis_options
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-atom/dartlang/issues/245#issuecomment-134412457>.
>
-- 
Daniel Joyce

The meek shall inherit the Earth, for the brave will be among the stars.

**Comment by DanielJoyce** [comment]
Not working for me. Dart analyzer continues to go into directories when I have told it to exclude them.

**Comment by DanielJoyce** [comment]
Dart Analyzer status in atom says 1.7.0, but dartanalyzer --version reports 1.11.3

**Comment by DanielJoyce** [comment]
This seems to be pretty bleeding edge, is this supported by current stable sdk?

**Comment by mkazlauskas** [comment]
Seems like you have to pass in an argument: https://www.dartlang.org/tools/analyzer/

**Comment by devoncarew** [comment]
This is only supported by the dev channel SDKs - 1.12.0. The number the analysis server reports is not related to the sdk version.

And newer analysis servers work much better with the atom plugin - there have been a number of bug fixes. You'll probably want to grab a dev sdk.

**Comment by mkazlauskas** [comment]
I can confirm that it works using dev channel SDK. I would recommend adding this to README.

**Comment by devoncarew** [comment]
fixed using a `. analysis_options` file
