### ISSUE TITLE
Grouping analysis options in settings page?

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#249]
![screen shot 2015-08-25 at 2 06 31 pm](https://cloud.githubusercontent.com/assets/5479/9479535/a3f70348-4b32-11e5-8e8c-1088dbc66b1c.png)

Could we group show infos, show todos, filter warnings about JavaScript, etc into a discreet group of settings? Right now, everything is under a big "Settings" group.

**Comment by devoncarew** [comment]
We need to wait for a bug fix in atom to land; should be in 1.0.8.

**Comment by sethladd** [comment]
Ah, cool!

**Comment by devoncarew** [comment]
We have fewer settings in here now.
