### ISSUE TITLE
smart quote insertion is annoying

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#250]
The smart quote insertion makes it harder to fix bad code with incorrect quotes. You have to delete a lot of auto-inserted quotes.

For example, start with this:

var x = .;

This is incorrect, so try to put quotes around the period to get "."

First you put a quote before the . and get:

var x = "".;

So, you have to delete the second quote, and add the trailing quote to get:

var x = "."";

Then delete the trailing quote again.

It seems like at least for the second case, it should be smart enough not to not to insert a second quote, since it converts working code to broken code?

**Comment by devoncarew** [comment]
You can toggle the smart insertion behavior in the settings for the `bracket-matcher` package. I keep the settings on, but do end up fighting with the smart quotes from time to time. Above, if you were to select the `.` and type `"`, it would be surrounded by quotes.
