### ISSUE TITLE
Would be nice to be able to not show warnings from packages/

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-atom/dartlang#252]
Maybe this is already possible?  Normally I want to see warnings in packages/ but right now I'm working around INFO warnings in intl.dart: https://github.com/dart-lang/intl/pull/76

**Comment by eseidelGoogle** [comment]
This is a pretty low priority issue for me.  Just figured I should file.

**Comment by devoncarew** [comment]
Cool. We had one other report of this. We shouldn't be showing warnings from the packages/ dir. What repo is this happening in for you?

**Comment by eseidelGoogle** [comment]
a local project which Atom created for me. I can push it to github, but right now it's not even a git repo.

**Comment by devoncarew** [comment]
I'm guessing these warnings don't show up until after you've navigated to the file once?

**Comment by eseidelGoogle** [comment]
http://filebin.ca/2DVK5lM6wSvT/grid.tgz

**Comment by eseidelGoogle** [comment]
Not sure.  I had more than one project open in the same atom workspace.  The other project I had open used this library, this one didn't.  However, Sky now depends on intl as of yesterday.

**Comment by devoncarew** [comment]
@brianwilkerson @stereotype441

It looks like pub is creating dart files in `.pub/deps/debug/intl/`.

**Comment by devoncarew** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/24212; thanks for the report.
