### ISSUE TITLE
Removing Sky from Dart plugin

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#257]
Tracking issue. We probably want to remove the "create new Sky project" from the Dart plugin. It's a bit odd that the generic Dart plugin has such specific support for a particular toolkit.

This assumes, of course, that we can build a separate Sky plugin for Atom.

**Comment by jlambright** [comment]
If creating a [Stangehand](http://stagehand.pub/) based project could also an option, why not leave it.

**Comment by devoncarew** [comment]
Done! A `flutter` plugin is published, and we're iteratively moving Flutter UI contributions into it.
