### ISSUE TITLE
Should variables be colored differently than type annotations?

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#258]
For example, for code like `Class FooBar;` both are yellow.

![screen shot 2015-08-27 at 10 49 31 am](https://cloud.githubusercontent.com/assets/5479/9528449/60ff6e68-4ca9-11e5-94c4-ffce69da9e03.png)

I would image the variable to have a different color than the word `Class`, which is a type annotation.

**Comment by devoncarew** [comment]
Our syntax highlighting is written based on Dart naming conventions. So, `Class fooBar` will look correct; `Class FooBar;` won't.
