### ISSUE TITLE
ctrl+click jump to declaration not working

### ISSUE THREAD

**Issue by johnmccutchan** [dart-atom/dartlang#26]
On Linux ctrl+click on a type or variable doesn't jump me to the declaration. F3 does.

**Comment by devoncarew** [comment]
How about alt-click? We're using alt (option) on a mac. I'm used to command-click being used for jump to declaration, but that's mapped to multiple cursors for atom.

If ctrl-click is more familiar we can switch to that. Atom is also generally uber configurable, so I could see a pref at some point.

**Comment by johnmccutchan** [comment]
Most keyboard shortcuts in Linux are ctrl+. Alt+click is consumed by the window manager to move the window. I would rather avoid adding a preference for something like this and just have Atom on Linux work out of the box.

**Comment by devoncarew** [comment]
Cool, thanks for the feedback. We _may_ move over to using this package: https://atom.io/packages/hyperclick to handle some of the UI of jump-to-declaration, including deciding what modifiers+click cause a jump. It looks like they use alt-click on linux. If that's generally a problem for linux users, we can contribute a patch to them to change to ctrl+click.

**Comment by radicaled** [comment]
We can have environment specific keymaps in Atom -- so we can adjust our default keymaps depending on Windows / Mac / Linux without having to force everyone to use the same key combos.

**Comment by radicaled** [comment]
Taken from: https://github.com/sedabull/new-file-plus/blob/master/keymaps/new-file-plus.cson

```cson
'body.platform-darwin':
  'cmd-n': 'new-file-plus:toggle'

'body.platform-linux, body.platform-win32':
  'ctrl-n': 'new-file-plus:toggle'
```
