### ISSUE TITLE
Unclear how to trigger a Quick Fix

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#261]
For example:

![screen shot 2015-08-27 at 12 53 11 pm](https://cloud.githubusercontent.com/assets/5479/9531400/a0f9a9e6-4cba-11e5-8500-77cf95faeee6.png)

How do I easily solve this problem?

Strawman: Would expect something like a link/message that says "Quick Fix available", which is displayed near the warning itself.

**Comment by devoncarew** [comment]
This is blocked on https://github.com/dart-lang/sdk/issues/23874. I'd love to be able to do this -

**Comment by devoncarew** [comment]
done!
