### ISSUE TITLE
pub is gone from right-click

### ISSUE THREAD

**Issue by rattaro** [dart-atom/dartlang#262]
version:  dartlang 0.4.0, atom 1.0.8
platform:  windows, fedora
problem:  right-click on pubspec.yaml no long has the "pub get" and "pub upgrade" options.

**Comment by devoncarew** [comment]
Can you try re-starting atom and re-verifying this? I believe we have issues when upgrading the plugin - old portions of the plugin can continue running and cause issues. I'd like to verify that this is not the case here.

**Comment by rattaro** [comment]
On Windows:  I uninstalled it.  Deleted the .atom file.  Reinstalled Atom.  Reinstalled Dartlang and Linter.
right click on pubspec.yaml still is missing the previous 'pub' options that were previously there.  I will test this on Fedora tomorrow and repost.

**Comment by rattaro** [comment]
I just found the problem.  If you right-click either the icon or the "pubspec.yaml" words, you do not get the options for pub.
Work around:  select the pubspec.yaml row, and then right-click on EITHER SIDE of the "icon + pubspec.yaml", and you will get the 'pub' options.  i.e. right-click on the blank space on the same row.
Verified on Windows and Fedora.

**Comment by devoncarew** [comment]
Ack, confirmed. Thanks for the report!
