### ISSUE TITLE
Dartdoc command should return getter doc comment if setter doc comment is not set

### ISSUE THREAD

**Issue by benjic** [dart-atom/dartlang#264]
Dart [doc comment style guide][0] suggests only documenting a getter when documenting a class variable. When the dartlang doc comment command is issued for a setter with this convention nothing is returned in the hover. 

As a consumer of the dartlang plugin in atom I should receive consistent documentation that is correctly formatted via the style guide. If a setter does not have a doc comment it should return the comment of it's reciprocating getter.

![1440734989](https://cloud.githubusercontent.com/assets/135916/9563390/74a2a9ac-4e3f-11e5-83bf-5170c54e6ef1.png)

![1440734999](https://cloud.githubusercontent.com/assets/135916/9563391/7d08c932-4e3f-11e5-9728-bb04fb5faf26.png)

[0]: https://www.dartlang.org/articles/doc-comment-guidelines

**Comment by benjic** [comment]
Looking at the source for the dart plugin it is the analyzer that determines the doc comment for a given symbol. I've filed a issue with the SDK; Please close the issue at your leisure.

https://github.com/dart-lang/sdk/issues/24234

**Comment by devoncarew** [comment]
Cool. I agree w/ this issue - we should show the intended docs for an element, even if in some cases they're defined on a related element.
