### ISSUE TITLE
Error messages cover up the cursor position when typing near the bottom of the window

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#265]
To reproduce:
 - open a Dart file large enough that the scroll bar appears
 - enter some bad code on the last line: "this.foo;"
 - notice that the code you just typed is covered up completely. (I see three errors and a warning.)

It seems like when displaying a bunch of new errors and the cursor is close to the bottom of the window, the window should automatically scroll to keep the cursor in view. That is, it should stop displaying the lines at the top of the window rather than the bottom to fit the smaller space.

**Comment by devoncarew** [comment]
This has been addressed in https://github.com/dart-atom/dartlang/pull/260. That PR has landed - I'm hoping to publish a new version ~tomorrow with that change and a few others.
