### ISSUE TITLE
right click -> go to declaration doesn't work

### ISSUE THREAD

**Issue by johnmccutchan** [dart-atom/dartlang#27]
Pressing F3 takes me there but the menu item appears to do nothing.

**Comment by radicaled** [comment]
@devoncarew the menu items are provided by Atom's `symbol-view` package. It's a default package. We can override this command, see if its been executed in a Dart file, and then do the same behavior as F3. That's what `atom-typescript` does.

**Comment by devoncarew** [comment]
+1, that sounds great
