### ISSUE TITLE
Does this package still require the linter package?

### ISSUE THREAD

**Issue by austincummings** [dart-atom/dartlang#276]
Seeing as how this package now provides its own error view. Does this package still need the linter package? Would it be appropriate to remove the message that tells the user the linter package is required?

**Comment by devoncarew** [comment]
It still adds value; we use it to display the errors and warnings within the editor. It's much more optional now though; I removed the message in https://github.com/dart-atom/dartlang/pull/278.

Hopefully in the future the linter package will be split into a model for the lints and a UI. That would make it easier for packages to host their own UI on top of lints.
