### ISSUE TITLE
delete command doesn't actually delete

### ISSUE THREAD

**Issue by rattaro** [dart-atom/dartlang#282]
Select a file from the tree
right-click and choose "delete"
The file does not delete.

"cut" also does not work either.

The only way to delete files is through the file manager or the command line.

**Comment by devoncarew** [comment]
I am able to delete files myself. What platform is this for? Can you disable the dart plugin, restart, and see if you still have the issue? I'm not sure this is related to the dart plugin, so would like to verify that. Thanks!

**Comment by rattaro** [comment]
Oops.  This looks like an Atom problem, not the dart plugin.  I'll investigate issues over there.  Sorry!
