### ISSUE TITLE
info-level problem reports shouldn't turn indicator red

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#284]
Previously my project had no errors, but after the latest upgrade it says there are "5 issues" at the bottom of the window, all of which are TODO comments. It's okay to point out TODO's, but since they are at INFO level, it seems like the indicator light shouldn't be red?

**Comment by skybrian** [comment]
I see now that there's a way to turn off info-level warnings so this is lower priority.

**Comment by devoncarew** [comment]
Yeah, that `5 Issues` contribution comes from the `linter` plugin. We'll need to send them PRs to either remove their contribution to the status line, or display the summary differently on info/warning/error level issues.

**Comment by devoncarew** [comment]
I opened an issue on the `linter` plugin; looks like we'll get an API change that will help us out here.
