### ISSUE TITLE
outline view is blank

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#285]
I just see the filename at the top. Seems like it shouldn't be on by default until it's ready?

This is in 0.4.2.

**Comment by skybrian** [comment]
Like in #287 this seems to have to do with how I open atom. If I cd to my project directory and open it using "atom .", I get this error. It works if I don't use the symlink.

**Comment by devoncarew** [comment]
Closing in favor of https://github.com/dart-atom/dartlang/issues/344.
