### ISSUE TITLE
"invalid file" when formatting a Dart file

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#287]
The error message is: "Error during `edit.format`: invalid file." 

This seems to have to do with how I open atom. I have a symlink to my work directory. If I use "cd" to enter the directory using the symlink, and then run "atom .", I get this message. If I go to the same directory without using the symlink and open atom, it works fine.

This is in 0.4.2.

**Comment by devoncarew** [comment]
Do most other things in the file work? Errors and warnings, F1 for help, navigation?

It sounds like in your setup the path atom's run from is different from the canonical path of the source files?

**Comment by skybrian** [comment]
Yes, I think it has something to do with the canonical path being different. However, I just tried using a symlink on my Mac and didn't reproduce it.

I didn't notice a lot broken but I'll check next time I'm in the office (probably Tuesday.)

**Comment by devoncarew** [comment]
Closing as https://github.com/dart-atom/dartlang/issues/344 is more specific.
