### ISSUE TITLE
pub serve as an option

### ISSUE THREAD

**Issue by rattaro** [dart-atom/dartlang#295]
I would like to see pub serve as an option, along with the other pub commands.  Using Dartium in development is really nice, but the effort to activate pub serve is cumbersome.

Current situation:
open command line
navigate to location of pubspec.yaml
type in 'pub serve'
open up Dartium

Requested option:
right click application tree
select 'pub serve'
pop up in top requests port
open up Dartium

**Comment by devoncarew** [comment]
Related to https://github.com/dart-atom/dartlang/issues/233.

And while serve is not exposed, _some_ of the pub commands are already available (get / upgrade / activate / global run / run). You can find more into here: http://dart-atom.github.io/dartlang/#getting-started.

**Comment by tsv2013** [comment]
+1 for pub serve

**Comment by Tomasito665** [comment]
+1 for 'pub serve' command in dartlang. It would be really handy!

**Comment by devoncarew** [comment]
Closing in favor of #585 - it's essentially the same issue.

**Comment by patoezequiel** [comment]
+1 it would help a lot!

**Comment by KOGI** [comment]
+1
