### ISSUE TITLE
Turning on "Format current file on save" maybe shouldn't show an info box every time.

### ISSUE THREAD

**Issue by iansf** [dart-atom/dartlang#301]
It is a bit distracting to have the little green box in the corner let me know that the atom plugin did something every time I save the file I'm working on.  Perhaps it should only give a message in that mode if there was an error?

**Comment by devoncarew** [comment]
+1, the auto-format mode should be pretty quiet.

**Comment by devoncarew** [comment]
I'm not seeing it notifying on each save. If there's a syntax error, it does complain on each save, but that display a red error toast.

**Comment by radicaled** [comment]
What message are you seeing? "Format successful" should only show on manual formatting; format-on-save will do it silently via a separate mechanism.

**Comment by iansf** [comment]
I think this was due to some inconsistent state in atom.  Previously it was giving me something like "Successfully formatted" or "No formatting needed" (not exact quotes) each time I saved, but I restarted atom and possibly updated the dartlang plugin, and I no longer see those issues.  Closing.
