### ISSUE TITLE
"Getting Started..." points to nowhere

### ISSUE THREAD

**Issue by iposva-google** [dart-atom/dartlang#305]
In particular it tries to open this URL which apparently does not exist:
https://github.com/dart-atom/dartlang/blob/master/doc/getting_started.md

According to the CHANGELOG.md which is accessed from "Release Notes" I am at "## 0.4.2"

**Comment by devoncarew** [comment]
That moved to here: http://dart-atom.github.io/dartlang/. The latest version is `0.4.3`; it should point to the correct place.
