### ISSUE TITLE
Clicking "Create issue on the dartlang package" opens error page

### ISSUE THREAD

**Issue by iposva-google** [dart-atom/dartlang#308]
Trying to file issue #307 using the convenient link I was greeted by this error page:
414 Request-URI Too Large

**Comment by devoncarew** [comment]
Thanks for the report! Atom's `notification` package sends that info to the github repo as an http GET. The size of the stack traces for dart2js compiled code blow throw the browser limit for url lengths.

Reported here: https://github.com/atom/notifications/issues/89.
