### ISSUE TITLE
linter markers sometimes wrong

### ISSUE THREAD

**Issue by radicaled** [dart-atom/dartlang#31]
Write this code:

```dart
void main() {
  return;
  if (true) { // dead code marker should be here.
  }
}
```

then change it to this:

```dart
void main() {
  return;

  
  if (true) {
  } // dead code marker shows up here.
```

possibly an issue with linter 1.12?

**Comment by devoncarew** [comment]
I have seen this as well. I have not been able to track down a common pattern for why its happening.

**Comment by radicaled** [comment]
With `logging: 'finer'` I can see that the analysis server is consistently returning the right position despite what's being displayed. Is it possible that some of the caching code recently added to ErrorRepository is not discarding the cache sometimes?

**Comment by radicaled** [comment]
This is probably it: https://github.com/dart-atom/dartlang/blob/master/lib/error_repository.dart#L104

So if the error message doesn't change, but its position does, then this will return the old, cached value, which has the incorrect position.

**Comment by radicaled** [comment]
Actually, maybe I read that code wrong. It's been a long day.

**Comment by devoncarew** [comment]
Hmm, could also be a bug in translating analysis server positions to atom ones?

**Comment by devoncarew** [comment]
I think this is a bug in the analysis server. It's sending back out-of-date locations. If you do a re-analyze sources, then the location comes back as being correct.

Possibly this was masked by doing a removeOverlay/addOverlay instead of a changedOverlay call.
