### ISSUE TITLE
Contrast pretty low on web page

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#312]
![screen shot 2015-09-10 at 4 40 06 pm](https://cloud.githubusercontent.com/assets/5479/9792923/ade77dd8-57da-11e5-8bc5-7299dec0e062.png)

**Comment by devoncarew** [comment]
That's controlled from here: https://github.com/dart-atom/dartlang/blob/gh-pages/_posts/2014-01-01-intro.md and here: https://github.com/dart-atom/dartlang/blob/gh-pages/_config.yml#L29

**Comment by devoncarew** [comment]
Fixed, but contributions welcome :)
