### ISSUE TITLE
Feedback and diagnostics if analysis server crashes or spins

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#32]
Let's signal to the user if the analysis server crashed (or is spinning at 100%), so the user can restart. Or, let's automatically restart AS and let the user know.

What kind of heartbeat should we send? How best to know when we should restart the AS?

Also, it might be helpful to send a ping to the AS and get a dump from the observatory, which we can then give to the user to include in their bug report. We have an easy single HTTP GET to get stack traces from all isolates in the VM.

**Comment by devoncarew** [comment]
We've plumbed in a bunch of this.
