### ISSUE TITLE
Start analyzer if a project has .dart files

### ISSUE THREAD

**Issue by gsathya** [dart-atom/dartlang#320]
Currently we introspect a build file looking for [dart targets](https://github.com/dart-atom/dartlang/blob/master/lib/projects.dart#L288) or look for [.pubspec/.packages](https://github.com/dart-atom/dartlang/blob/master/lib/projects.dart#L33) before starting the analyzer. 

In many dart projects, we rarely use the dart targets specified("dart_library" or "//dart/build_defs"), but instead use higher level build targets, which means the analyzer never starts for those projects.

Can we start the analyzer if it sees a .dart file in the project directory? What are the concerns with this approach? Even with huge project dirs (which Atom can't really support that well), I don't think it'll take too much time to find if there is a .dart file.

**Comment by gsathya** [comment]
Hey @devoncarew  -- would you be open to a patch for this :smile: ? or do you have any reservations against this change?

**Comment by devoncarew** [comment]
I have hard to quantify worries about starting an analysis context for any top level directory w/ dart files. The analysis server is a heavyweight process - starting it consumes a lot of cpu and memory. And the resources used may be disproportionate to the number of files you're editing at the time. If you open a subdir of a dart project, atom may only see a few files from the project. But the root of the analysis context may sit several directories up, encompassing a lot of files.

The best case scenario is a 100% reliable way of determining the directory to start an analysis context in. It sounds like that doesn't exist for BUILD files?

We could instead let the user opt-in manually. So, have a context menu to mark a directory as a dart project. We'd need to persist that info and figure out the right UI.

**Comment by devoncarew** [comment]
Also, @gsathya - thanks for the offer of a patch! Totally open to something, once we can narrow down what a good solution would be.

**Comment by gsathya** [comment]
> The best case scenario is a 100% reliable way of determining the directory to start an analysis context in. It sounds like that doesn't exist for BUILD files?

Yeah, agreed. 

> We could instead let the user opt-in manually. So, have a context menu to mark a directory as a dart project. We'd need to persist that info and figure out the right UI.

It could be a config setting like how tern does autocomplete for js -- https://atom.io/packages/atom-ternjs (look at loadEagerly). 

It could be a context menu as well apart from being a config setting and whenever the user clicks on the option in the context menu, we can update the config setting to persist that info.

Thoughts?

**Comment by devoncarew** [comment]
I didn't parse exactly how they're doing it, but some thoughts:

- a user config setting would work but be a bit course. You'd need to use a string field to contain a list of paths which are dart projects. To the user, it would look something like `/foo/bar/baz_project:/baz/quz_project` - not great UX and harder for the user to maintain.
- a marker file would work - like `.projectTypeDart` - but I don't know that all many users would appreciate a new top-level file, and one that they'd need to commit to scm.
- a new atom command - `mark as dart project` or some such - might work best. It would act on the currently selected project. It _might_ prompt the user first to confirm / edit the path. You could perhaps use the same command to toggle the project off. The user has to know the command is there to run it, but if it's an infrequent use case perhaps that's ok.

**Comment by devoncarew** [comment]
We may look for the presence of an `.analysis_options` file here...
