### ISSUE TITLE
Easy way to send feedback about the plugin

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#33]
I'd love to make it easy for users to send us feedback (issues, bugs, enhancements).

Maybe under Packages / Dart ?

**Comment by devoncarew** [comment]
There's this in the settings dialog:

<img width="302" alt="screen shot 2015-07-09 at 4 39 00 pm" src="https://cloud.githubusercontent.com/assets/1269969/8609357/158b128c-2659-11e5-94db-2ae7209dc8ed.png">

That's standard to atom. We can add some additional UI somewhere as well - that menu item sounds good.
