### ISSUE TITLE
Better way to open the outline view

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#333]
The sidebar has close button now, which is handy but not obviously reversible. It looks like I need to go to settings to open the sidebar again.

It seems like there should be a toggle for it, like there is for the errors footer?

**Comment by devoncarew** [comment]
Agree, but I'm not sure where to put the 'open outline view' button :)

We can have a small toggle overlying the top right of a dart editor, for people that want an outline view. Or collapse the width down to 20px-40px or so, so a close it more of a collapse.

**Comment by skybrian** [comment]
I also noticed that if you have a split screen, there are two close buttons. Clicking one closes both outlines.

**Comment by skybrian** [comment]
A thought: could it be a menu item?

Packages => Dart => Toggle Outline View

**Comment by devoncarew** [comment]
Sounds good. It may also make sense in the `View` top level menu.

**Comment by skybrian** [comment]
Hmm, it seems to under "View" already. Works for me.

**Comment by devoncarew** [comment]
Hmm, https://github.com/dart-atom/dartlang/commit/d2eb380a7e2fb27d2516d7cba6110e4f6c8a20fc. I have a bad memory -

**Comment by devoncarew** [comment]
Also, I'm working on a toolbar for the dart plugin, to improve discoverability of which apps you can launch and what devices you can launch them on. That'll be a potential place to put a toggle outline button.
