### ISSUE TITLE
Prompt the user to run pub (at least once in the beginning)

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#336]
Consider this flow:

* clone a git repo
* open the new directory in Atom

The user is presented with potentially tons of errors, mainly because pub was never run.

![screen shot 2015-09-17 at 4 39 51 pm](https://cloud.githubusercontent.com/assets/5479/9948775/d71a088a-5d5a-11e5-90e2-9f44ba719e61.png)

Should we detect that pub was never run and help the user understand that all the warnings might be because they need to install their dependencies?

Atom 1.0.12, dartlang 0.4.5, SDK 1.13.0-dev.2.0 running on macos.

**Comment by sethladd** [comment]
It might be easy to detect this state... is there a pubspec.yaml and no pubspec.lock or .packages? If so, need to run pub get!

**Comment by devoncarew** [comment]
Possibly related to #335 - in some cases we may want to auto-run pub, in others auto-prrsent to the user the option to run pub.

**Comment by devoncarew** [comment]
fixed - we detect missing or out of date .packages files
