### ISSUE TITLE
After 5 minutes with dart/sdk open, Atom tree browsing slows to a crawl

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#34]
Clone the dart/sdk repo.
Open a single Dart file.
Leave Atom for 5 minutes.

Expected: tree browsing is fast

Actual: tree browsing is very slow.

**Comment by sethladd** [comment]
Not sure if this is a bug in Atom, or we're analyzing way too much?

**Comment by sethladd** [comment]
![screen shot 2015-07-09 at 3 55 43 pm](https://cloud.githubusercontent.com/assets/5479/8608767/f8c84116-2652-11e5-8e0b-942a15958c95.png)

**Comment by radicaled** [comment]
You can disable the package without uninstalling it by going to Settings -> Packages (command palette), searching for dartlang, and hitting disable. Then we can see where the problem is originating from.

**Comment by sethladd** [comment]
Good call! I'll give that a shot.

**Comment by devoncarew** [comment]
Also, open the analysis server status dialog will give you a sense of a runaway analysis server. That, and in the activity manager, the `dart` process will be pegged at 100%.

**Comment by sethladd** [comment]
Indeed, opening the dart/sdk folder sends apparently EVERYTHING to the analysis server. We have a scalability issue here.

**Comment by sethladd** [comment]
See https://github.com/dart-atom/dartlang/issues/32

**Comment by devoncarew** [comment]
Covered by #609.
