### ISSUE TITLE
errors + warnings if lib has foldername with underscore

### ISSUE THREAD

**Issue by MikeMitterer** [dart-atom/dartlang#341]
Try to install this little sample Dart-App: https://cdn.rawgit.com/MikeMitterer/dart-material-design-lite/master/site/downloads/simple.zip and **pub update**

This gives you all kind of errors and warnings. The problem is the `.pub/deps/debug/mdl/lib/_templates` (probably the underscore) - after deleting this folder the errors are gone.

![screenshot-1859](https://cloud.githubusercontent.com/assets/116654/10012445/728352a8-6108-11e5-9956-cb7fce8956b6.png)

---
Atom 1.0.15, dartlang 0.4.6, SDK 1.12.1 running on macos.

**Comment by devoncarew** [comment]
Thanks for the report! This is a known issue in the analysis server - https://github.com/dart-lang/sdk/issues/24212. You should also be able to remove the spurious issues by running the atom command 'reanalyze sources'.

**Comment by devoncarew** [comment]
(will try and repo with the sample just to be sure)
