### ISSUE TITLE
Request for Atom to inform the user if their Dart SDK it out of date

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#343]
We do this in WebStorm, might be a good idea to do this in Atom, too.

We can ping the same JSON that drives the homepage. e.g. polling https://storage.googleapis.com/dart-archive/channels/dev/release/latest/VERSION

Atom 1.0.15, dartlang 0.4.5, SDK 1.13.0-dev.2.0 running on macos.

**Comment by devoncarew** [comment]
We should direct users to the platform specific download page, e.g. `https://www.dartlang.org/downloads/windows.html`.

**Comment by devoncarew** [comment]
Show this as a dismissable toast? Add a contribution to the status line? Some possible icons:
https://octicons.github.com/icon/cloud-download/ ? https://octicons.github.com/icon/desktop-download/ ? https://octicons.github.com/icon/issue-opened/ ? https://octicons.github.com/icon/shield/ ? https://octicons.github.com/icon/megaphone/

**Comment by sethladd** [comment]
+1 for a dismissable toast.

I like the "desktop download" icon, FWIW.

We worked through a bunch of UI and logic for this in WebStorm, I think most of that should be portable. Here's the issue: https://youtrack.jetbrains.com/issue/WEB-10234

First, I wonder if there is a Dart library for "checking if a new version of the Dart SDK exists", since this has to be fairly common.  cc @kevmoo because I think he might have written this?

In the prefs, the user can say "notify me when there's a newer version of the Dart SDK". It should default to "on".

If the developer has a dev channel installed, we tell them if there's a newer dev channel OR stable channel available.

if the user has stable channel installed, we only tell them if there's a newer stable channel.

When there is a newer version, we can point them to: https://www.dartlang.org/downloads/

**Comment by eseidelGoogle** [comment]
It looks like we have this now.

**Comment by sethladd** [comment]
Nice!
