### ISSUE TITLE
New project need a bit of cleanup

### ISSUE THREAD

**Issue by lukechurch** [dart-atom/dartlang#346]
If you have one project open you want to add another one, the related choices displayed are the following:

File Menu:
New File
Add Project Folder

In the context menu:
New File
New Folder
Add Project Folder

====

There's a consistency issue (no New Folder in the file menu).
There's also a terminology issue. Is there a difference between 'a folder' and a 'project folder'?
If there is, how do I get a new 'project folder', which is what I think I want?

I think this probably just needs a bit of cleanup?

**Comment by devoncarew** [comment]
@lukechurch, these are contributed by the core atom code. We can re-file this against their repos if we want. https://github.com/atom

**Comment by lukechurch** [comment]
Ahh, I see. Do they need a more precise recommendation if they're going to get actioned inside the Atom repo? I imagine their noise level is a little higher?

**Comment by devoncarew** [comment]
Yup, pretty clear guidance, and / or a PR.
