### ISSUE TITLE
Option to see code quality notifications on only the code in the current project

### ISSUE THREAD

**Issue by lukechurch** [dart-atom/dartlang#348]
I'm working on a project which by necessity pulls in a lot of 3rd party packages. Some of them have hints associated with them.

This is noise, but also means that I never get the happy reward feeling for having a 'clean' project, so I'm not incentivised to fix hints even in my own project.

Proposed changes:

1. In the RHS near the info bullet list which packages the issues are associated with check boxes. By default issues are only displayed for the the code that is currently loaded into the project (i.e. not via the packages symlink).

2. Don't use a red issues indicator for hints in the bottom bar, only use that for serious warnings and errors.

**Comment by devoncarew** [comment]
Can you add a screenshot to help me get context? Thanks!

**Comment by devoncarew** [comment]
> 3rd party packages. Some of them have hints associated with them.

We shouldn't be showing issues for packages at all. Can you clarify when this is happening?

**Comment by lukechurch** [comment]
Ah - ok, poking at this a little more, it seems that what is happening is:

pub get is adding a '.pub' folder. When I add the whole folder, that is getting added in for analysis. I'm then seeing warnings etc. for those via the .pub folder.

**Comment by devoncarew** [comment]
Yeah, lots of people are seeing this on sky - it may be our number 1 issue right now. https://github.com/dart-lang/sdk/issues/24212

Any help motivating a fix is appreciated.
