### ISSUE TITLE
Inline display of errors should go away as soon as I hit a key

### ISSUE THREAD

**Issue by lukechurch** [dart-atom/dartlang#349]
If I have an inline error displayed, and I edit the location, I expect the inline error to go away and stay away for a short period, giving me a chance to fix up the code at that region before telling me it's wrong again.

This specific case I have a the moment looks like:

abstract class X {
  this.
}

Enter the 'this.' - Pause to think - I get an error, at the cursor, that's okish.

Press backspace the error doesn't go away, it's replaced with 'Unexpected token 'this''. Whilst correct, that's not helpful. I am now fixing the problem so would like to not be interrupted again for a little while.

It continues to not go away as I backspace away the rest of the 'this'.

**Comment by devoncarew** [comment]
I think this is a dup of https://github.com/dart-atom/dartlang/issues/270; I'll move your comments into there.
