### ISSUE TITLE
No clear way to dismiss the analysis server status dialog

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#35]
Open up "analysis server status".

How to dismiss?

Esc doesn't work. Clicking out of the dialog doesn't work.

"cmd-shift-p and then esc" does it :)

**Comment by devoncarew** [comment]
Yeah, this needs a close box. Not all the atom model dialogs have them - I'm not clear on the UI conventions here. Currently you have to be in a text editor and hit escape.

**Comment by radicaled** [comment]
Modals should always go away when "core:cancel" is received.  By default, that is bound to ESC on every platform.
