### ISSUE TITLE
Info/Hints are displayed as 'Trace' when displayed in bubbles

### ISSUE THREAD

**Issue by lukechurch** [dart-atom/dartlang#352]
The info markers should be consistently named 'Info' in the bubbles.

![image](https://cloud.githubusercontent.com/assets/2978182/10043105/3cf6f64a-61e8-11e5-9f21-cb5bdb70f857.png)

**Comment by devoncarew** [comment]
I opened a PR against the atom `linter` package for this -

**Comment by devoncarew** [comment]
Fixed in https://github.com/atom-community/linter/pull/919.
