### ISSUE TITLE
LHS gutter and dotted lines for warnings are the blue when they should be orange

### ISSUE THREAD

**Issue by lukechurch** [dart-atom/dartlang#363]
See e.g.

![image](https://cloud.githubusercontent.com/assets/2978182/10108378/7a907efa-63b8-11e5-9ed2-5b610b8b62c7.png)

The dashed underline and the gutter bar icon are blue - I think in this context they should yellow/orange?

I think I'm only seeing this problem on type signatures on methods, but can't be sure.

**Comment by devoncarew** [comment]
Are there two problems on this line? I think with the `linter` package currently, the last issue on the line will win for contention with the dot color. If you think that's the issue, I can re-file this.

**Comment by devoncarew** [comment]
Closing - please re-open if you see this again.
