### ISSUE TITLE
README says install linter, but that's hard to find

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#367]
I wonder if we can be more specific or helpful?

Setting up Atom on my home machine. The readme for our package says "Install linter", so I search for "linter" and I see a bunch of random options:

![screen shot 2015-09-26 at 7 56 21 am](https://cloud.githubusercontent.com/assets/5479/10118109/3962cf66-6424-11e5-9635-abaa425c69ff.png)

Not sure which one I want?

Scrolling way down, I find "linter".

Not sure if we can be more helpful, since this is a function of the Atom's package search.

Feel free to close if there isn't much we can do...

**Comment by devoncarew** [comment]
We can make the readme text more explicit about what to do, but I don't know that it would read as smoothly. Feel free to wordsmith something -

Long term, we'd want something like https://github.com/dart-atom/dartlang/issues/51, either done from us or provided by the atom platform.

**Comment by steelbrain** [comment]
@devoncarew We're using my [`atom-package-deps`](https://www.npmjs.com/package/atom-package-deps) to install `linter` in most linter providers, it's super-easy to setup. I'll recommend you give it a try.

**Comment by sethladd** [comment]
Thanks for the tip!

**Comment by devoncarew** [comment]
Thanks! We'll give it a try.

From browsing the code, it looks like it shells out to `apm`. Do you have a sense for how reliable that is? Would users have needed to set up apm on their path, or would this work for a typical install of atom on the various OSes?

**Comment by steelbrain** [comment]
@devoncarew It shells out to `apm` because even the settings view does that. I would say it's **very** reliable because we're using `atom.packages.getApmPath()` to get the path of it, the reliability of it is proved by every single person who downloads `atom-typescript`, `ionide-installer` or any `linter-*` packages. It has been confirmed to work with all major OSes.

**Comment by devoncarew** [comment]
We auto-install is now, if it's not already installed.
