### ISSUE TITLE
${x.y} expressions syntax highlighted as string 

### ISSUE THREAD

**Issue by lukechurch** [dart-atom/dartlang#368]
![image](https://cloud.githubusercontent.com/assets/2978182/10123989/98bd32ea-6540-11e5-890f-8f551dcb96ba.png)

Expressions within the ${} should be highlighted as expressions - otherwise there is a potential for people to think that they've got the syntax wrong.

**Comment by kevmoo** [comment]
This appears fixed in v0.7.0 - 
![screen shot 2017-09-15 at 1 03 08 pm](https://user-images.githubusercontent.com/17034/30501173-3fba2c04-9a16-11e7-9ce7-4634dcfe5348.png)
