### ISSUE TITLE
Organize Directives doesn't delete duplicates

### ISSUE THREAD

**Issue by lukechurch** [dart-atom/dartlang#369]
I'm not sure if this issue is in the Analysis Server or in the plugin.

Organize directive is great, but doesn't delete duplicate usages. e.g. my current file has

```
import 'package:sintr_common/configuration.dart' as config;
import "package:sintr_common/configuration.dart" as config;
```

One of these should get deleted.

**Comment by devoncarew** [comment]
@scheglov

**Comment by scheglov** [comment]
Works for me.
These tests pass just fine.

```dart
  void solo_test_remove_duplicateImports_withSamePrefix() {
    _computeUnitAndErrors(r'''
import 'dart:async' as async;
import 'dart:async' as async;

main() {
  async.Future f;
}''');
    // validate change
    _assertOrganize(
        r'''
import 'dart:async' as async;

main() {
  async.Future f;
}''',
        removeUnresolved: true,
        removeUnused: true);
  }
```

```dart
  Future solo_test_OK_remove_duplicateImports_withSamePrefix() {
    addTestFile('''
library lib;

import 'dart:async' as async;
import 'dart:async' as async;

main() {
  async.Future f;
}
''');
    return _assertOrganized(r'''
library lib;

import 'dart:async' as async;

main() {
  async.Future f;
}
''');
  }
```

**Comment by scheglov** [comment]
Ah.. I see.
Different URI string styles.

**Comment by scheglov** [comment]
Hm... No, it still works.
One of these analyzer marks as unused, so directives organizer knows to exclude it.

Please provide a test case.

**Comment by devoncarew** [comment]
@lukechurch, can you post the version of the sdk you're using? If you use the `Packages > Dart > Send Feedback...` menu item, it'll create a one-line version string.

**Comment by lukechurch** [comment]
Atom 1.0.19, dartlang 0.4.6, SDK 1.12.1 running on macos.

**Comment by lukechurch** [comment]
If there's some form of upgrade you'd like me to do, please let me know :)

I'm guessing you can't repro this?

**Comment by devoncarew** [comment]
I can't repro. I'm on: `Atom 1.0.19, dartlang 0.4.7, SDK 1.13.0-dev.3.1 running on macos.`

**Comment by lukechurch** [comment]
OK, lets assuming this bug is going to go away then, and if I still see it after the 1.13 release I'll reopen. Sg?
