### ISSUE TITLE
Request to add option to enable mixins+super() flag for analysis server

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#370]
See https://github.com/dart-lang/sdk/issues/23772#issuecomment-143887683

Atom's UI will need to create an option to enable this feature.

Since this is used by Flutter, might make sense to invest in the UI or default to turning it on for everyone.

**Comment by devoncarew** [comment]
Looks like the AS setting is `enableSuperMixins`. Do we want a settings checkbox or to just turn this on by default? Happy to do either. We already have a lot of UI settings.

IMO though, this should be controlled on a per-project basis. Probably in `.analysis_options`. Having an AS wide setting means that every project you have open will get this setting - both ones you want and ones you don't. In additional, each developer on a project needs to enable this individually. Much better to have the setting in a file that gets revisioned with the project.

**Comment by sethladd** [comment]
> Do we want a settings checkbox or to just turn this on by default?

If enabling this feature by default is backwards-incompatible, then we need an option and default it to off. If this feature is transparent to existing code, then we can simply force it on.

> IMO though, this should be controlled on a per-project basis. Probably in .analysis_options.

Yes, that would be ideal.

**Comment by sethladd** [comment]
Thanks!
