### ISSUE TITLE
pub get/pub run on slightly different structured projects

### ISSUE THREAD

**Issue by lukechurch** [dart-atom/dartlang#373]
I have a project using a slightly modified setup for deploying to App Engine.

it has a structure:

```
- root
   - app.yaml
   - app
         - pubspec.yaml
         - bin
               - ....
         - lib
               - ....
```

I'm not being offered 'pub get' on the pubspec file, only Pub Run and Pub Global Run.

**Comment by devoncarew** [comment]
In `root/`, is there a `.packages` file? Or higher up in the directory tree? Is `root` the directory that you opened in Atom?

Just to verify, do this work better if you open the `app` dir in atom instead?

**Comment by lukechurch** [comment]
Hmmm. Having reloaded atom this seems to now be behaving correctly again. 

I'll close as can't repro and if it comes back I'll re-open.

There wasn't a .packages in root, there was one inside inside 'app'. I had root opened in atom.
