### ISSUE TITLE
"find next" in linux doesn't appear to work

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#375]
Report from a customer on Linux:

According to https://github.com/nwinkler/atom-keyboard-shortcuts , Find-Next is F3 on Linux. However, that doesn't work when the Dart plugin is installed.

Is this an issue with Atom, or the Dart plugin, or another plugin?

Also:

"shift+F3 does a find-previous
F3's behavior is odd
it sometimes does nothing, but sometimes it seems to go to a specific instance of the phrase I searched for
and then F3 again causes a flash but the highlight stays where it was before"

**Comment by sethladd** [comment]
Thanks for taking a look!

**Comment by devoncarew** [comment]
Looks like F3 on linux is bound to both find next and the dart jump to declaration command.

**Comment by devoncarew** [comment]
Somewhat related: on the mac, we're stepping on the find previous keybinding for `shift-cmd-G	dartlang:find-references`.

**Comment by krisgiesing** [comment]
I worked around this by 1) adding a new shortcut for jump-to-declaration, and 2) adding an override for the dartlang selector to set F3 back to find-next:

'atom-text-editor[data-grammar~="dart"]:not([mini])':
  'alt-e': 'dartlang:jump-to-declaration'
'atom-text-editor[data-grammar~="dart"]:not([mini])':
  'f3': 'find-and-replace:find-next'

**Comment by sethladd** [comment]
Can we use something else for jump to definition? Ideally, we don't have to squat on a generally well-known shortcut for Atom?

**Comment by krisgiesing** [comment]
As a complicating factor, I quickly realized alt-e was not a good choice because alt activates menus on Linux.  So alt-e is already bound to bring up the Edit menu. Sigh.

**Comment by devoncarew** [comment]
We can change, but it is sort of minefield. I've tried to aim for familiarity with other common tooling when the functionality isn't native to atom.

**Comment by krisgiesing** [comment]
Having done keyboard shortcuts for other applications, I have to agree with the minefield comment :)

**Comment by sethladd** [comment]
OK, let's plan to change it. Find next is a pretty common action to take.

**Comment by krisgiesing** [comment]
FWIW, I haven't actually been able to get an alternative shortcut for "jump to selection" to work. The first issue is that Atom shortcut selectors have to be declared only once, so the code I pasted above isn't correct (the third line should be deleted). Even with that fixed, though, none of the shortcuts I pick reliably execute the command.  It's weird; it seems to work sometimes but not always.

**Comment by devoncarew** [comment]
@krisgiesing, do other analysis related items work in files with 'jump to selection' issues? The outline view, or type hierarchy (F4)?

**Comment by krisgiesing** [comment]
Jump to declaration (sorry for typo above) works if I select it from the context menu. It doesn't work if I try to assign it as a shortcut.  I may be doing something wrong with respect to the key map file, but I can't figure out what; I did successfully restore F3's default behavior.

**Comment by devoncarew** [comment]
We'll adjust the default keybindings and see how that works. Do not know yet what the best-keybinding-least-likely-to-conflict is...

**Comment by devoncarew** [comment]
New proposal for linux keybindings:

`F4`: type hierarchy. It's familiar to existing tools, and doesn't seem to conflict on linux or mac.
`ctrl-F4`: find references. It doesn't conflict, and both it and type hierarchy do the same thing - open a set of search results.

jump to declaration. This moves the cursor - it doesn't show search results - so acts differently to the first two keybindings. Perhaps `F6`? This seems available. So many of the letter keybindings are taken, and it's difficult to find a free one where the letter makes some semantic sense with the name of the action.

**Comment by devoncarew** [comment]
cc @pq and @stereotype441 for fyi -
