### ISSUE TITLE
Incorrect errors and warnings when the same file is opened more than once

### ISSUE THREAD

**Issue by lukechurch** [dart-atom/dartlang#383]
I'm getting a lot of bogus errors and warnings, mainly around 'missing }' at the end of a file that is correctly terminated - this only appears to happen when there are two copies of a file open.

Repro steps:

- Open a project
- Open a dart file (say a.dart) , right click 'Split down' (gives you an RHS pane with the same file in it)
- Open another file in the RHS panel without closing a.dart. You should now have two copies open, one visible, the other not.
- In the LHS window start editing a.dart by inserting and removing white space, you'll see analysis errors start to appear

If you close the a.dart tab in the RHS panel, you'll no longer see these bogus errors.

**Comment by steelbrain** [comment]
@lukechurch A screenshot explaining it would be nice
