### ISSUE TITLE
F1 on the keyword async displays incorrect signature

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#388]
(was https://github.com/dart-lang/sdk/issues/24495)

```
derp() async {
return 1;
}
```

Put cursor on async, hit F1.

Expected: a blurb telling me what this fancy async thing is (I think this is the best thing to do here? or do we want to show the signature for the method?)
Actual: `() -> int`

Customer was using:

dart 1.12.1
dart plugin 0.4.8

**Comment by DanielJoyce** [comment]
Its worse, 

F1 gives ```()->dynamic```

**Comment by devoncarew** [comment]
We're getting the F1 text from the analysis server. Agree that some nice docs would be awesome when the user hits `F1` over a keyword, esp. one like async.

**Comment by sethladd** [comment]
Should we move this over to the SDK? Seems like we can do better than `() -> dynamic` when you mark a method as async.

**Comment by devoncarew** [comment]
Yup, moving to the SDK sounds good.

**Comment by sethladd** [comment]
Reopened the issue over in the SDK
