### ISSUE TITLE
Misleading menu option with no windows open

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#390]
Start Atom.

Ensure there are no windows/views.

Expected: Nothing under the Packages drop down

Actual: I see Dart with an arrow, but nothing under the arrow.

![screen shot 2015-10-05 at 2 31 30 pm](https://cloud.githubusercontent.com/assets/5479/10294253/ec810cd4-6b6d-11e5-874a-ffcdd27fba2a.png)

**Comment by devoncarew** [comment]
Agree this is misleading. This is a problem in the core platform however, and not something users will routinely encounter. Will close this out and we can revisit if is turns out it is impacting users.
