### ISSUE TITLE
Ovals sitting on top of text in console

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#393]
Not sure what these ovals are... run contexts? In any case, they are sitting on top of text in the console.

![screen shot 2015-10-05 at 2 52 40 pm](https://cloud.githubusercontent.com/assets/5479/10294718/e67a96ea-6b70-11e5-99bb-efb01bf3ec82.png)

**Comment by devoncarew** [comment]
Those are different running applications you can switch between.

We should be re-cycling the flutter launches here.

**Comment by sethladd** [comment]
reflowing the "tabs" might not be ideal:

![screen shot 2015-10-05 at 3 00 06 pm](https://cloud.githubusercontent.com/assets/5479/10294890/d26b17f0-6b71-11e5-969b-a9ebff1667f2.png)


+1 for recycling... I don't want multiple concurrent runs unless I'm actually working on different apps

**Comment by devoncarew** [comment]
Closing - will track in other bugs.

**Comment by sethladd** [comment]
Which other bugs? (for those following along)

**Comment by devoncarew** [comment]
Some things have landed - re-cycling flutter launches and trying to make the fact that the ovals act as tabs more apparent. This issue is also tracking some similar stuff: https://github.com/dart-atom/dartlang/issues/394
