### ISSUE TITLE
UI nits for the run contexts/outputs

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#394]
![screen shot 2015-10-05 at 2 52 40 pm](https://cloud.githubusercontent.com/assets/5479/10294723/f6b51f58-6b70-11e5-8d9c-dd62843eafa4.png)

I think I understand the bug to me "click me to debug this". Is that accurate?

Is the white square next to that supposed to me "stop"? If so, might I suggest using Red ? It took me a while to guess what the white square is. There's no hover-over hint, either.

It's not clear these are tabs, but I think they are supposed to be tabs? That is, select one to see the output of that thing.

I'm really concerned I have what appears to be four mobile apps running. Is that true? What's supposed to happen after I run a Flutter app repeatedly ?

Not clear if there's an "active" tab? Which tab means "the app running on your phone right now" ?

**Comment by devoncarew** [comment]
Thanks for the feedback! There's lot to iterate on here.

The selected tab is the blue one. We could make it clearer that these are tabs. I didn't want to take up as much space as a normal tab would have.

We should be re-cycling flutter runs, so you normally won't see this many running applications.

Can add some tooltips to help users know what's going on.

**Comment by sethladd** [comment]
recycling: yes, one tab per app

What does "flutter" mean, in the tab? How does it know that it's a flutter app? And shouldn't it be "Flutter" ?

Selecting different tabs doesn't change the app on my phone. Though it changes what tab is blue. But maybe this is solved when we start recycling tabs.

**Comment by devoncarew** [comment]
Urk. It is changing the running app, they're all just showing the same text, and don't update the scroll position as you cycle between apps. Definitely needs UI work.

**Comment by devoncarew** [comment]
- changed to re-cycle the flutter launch - you shouldn't see more than one flutter launch at a time now
- add some UI to make it clearer that the badges act as tabs (an underline beneath the tabs)
- save the scroll position when switching between tabs
- `flutter` is the type of launch. If run run a command-line app, you'll see `cli`
- tooltips added to help make it clearer what the button do
- I experimented with using red for the stop button - it didn't play well with the background color. We do have some constraints with the colors - we have to stay to a particular palette of colors, which themes can swap out. Will keep an eye out for usability improvements to the buttons

**Comment by sethladd** [comment]
> you'll see cli

I haven't seen this in action yet, but should we consider "Dart CLI" ? I don't know if the "Dart" context will be obvious...

> I experimented with using red for the stop button - it didn't play well with the background color

Maybe we need a different approach to the background color?

@lukechurch what's the current thinking w.r.t. colors for buttons? Is shape sufficient to hint at the button's purpose? Or should we work really hard to get the color right, too?  (I understand we should consider getting the UI right even for color-blind users, so maybe the discussion around color isn't that relevant)

@devoncarew there are other shapes to consider for Stop... such as a Stop Sign. A white square just doesn't say "stop" to me.

**Comment by devoncarew** [comment]
This is the low-hanging fruit for icons: https://octicons.github.com/

Happy to iterate on this; I'm trying to go for terseness and compactness in the UI, but don't believe that the current UI is clear enough to the user. Perhaps it's necessary to use actual tabs?

<img width="326" alt="screen shot 2015-10-18 at 7 12 39 pm" src="https://cloud.githubusercontent.com/assets/1269969/10568382/484af03a-75cc-11e5-9218-9ed94ebf2a6a.png">

I'd worry about the amount of vertical space that would use, esp. when you want the console to be ~compact, and there's generally just one launch at a time.

Perhaps a VC about various UI issues would help out -

**Comment by devoncarew** [comment]
Fixed in https://github.com/dart-atom/dartlang/pull/536.
