### ISSUE TITLE
Suggestion to make it more clear that the user can run something

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#395]
After I created a sample Flutter app via Atom, I wasn't sure what to do next. Run? Launch? Go?

Looked in Command Palette, searched for "flutter" or "dart", didn't see something that looked like "run".

Looked in menu, under Packages, Dart. Didn't see something that looked like "run".

Atom 1.0.19, dartlang 0.4.8, SDK 1.13.0-dev.2.0 running on macos.

**Comment by devoncarew** [comment]
Closing in favor of #541 and #553
