### ISSUE TITLE
Two copies of the plugin running after a plugin upgrade

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#397]
![screen shot 2015-10-06 at 10 28 03 am](https://cloud.githubusercontent.com/assets/5479/10316609/fff47768-6c14-11e5-9d2b-41bc05a94470.png)

I opened a new window, then "created new flutter project", and not sure exactly when, but two analysis views appeared.

Atom 1.0.19, dartlang 0.4.9, SDK 1.13.0-dev.2.0 running on macos.

**Comment by sethladd** [comment]
Ah, I think it created two apps! See below, there are two "main.dart" tabs. Each with a different path.

![screen shot 2015-10-06 at 10 29 52 am](https://cloud.githubusercontent.com/assets/5479/10316646/3aaf67b4-6c15-11e5-9c20-0f6397eb8225.png)

**Comment by sethladd** [comment]
I restarted Atom, and now I'm only creating a single new app.

**Comment by devoncarew** [comment]
We've seen this off and on for a while. We need a systemic solution to ensure that everything gets cleaned up when our plugin is deactivated. That's listeners to atom APIs, contributions to the DOM, periodic timers, and anything else that has a callback into our plugin.

**Comment by devoncarew** [comment]
This was caused by a dispose() method throwing an exception while the plugin was shutting down; no other dispose methods were called. We guard against this now.

**Comment by sethladd** [comment]
Thanks for helping track this down!
