### ISSUE TITLE
Sample Flutter app doesn't run, lib/main.dart not found

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#398]
Sorry, I can't copy out from the console. Here's a screenshot:

![screen shot 2015-10-06 at 11 09 14 am](https://cloud.githubusercontent.com/assets/5479/10317740/c6aa26f0-6c1a-11e5-94e3-a5110c66c2e1.png)

* sky_tools 0.0.16 is in the pubspec.lock (latest at this time)
* closed all my atom windows
* New window
* Packages, Dart, Create new Flutter app
* Waiting until done
* Cmd-R

Atom 1.0.19, dartlang 0.4.9, SDK 1.13.0-dev.2.0 running on macos.

**Comment by sethladd** [comment]
FWIW I stopped the run using the little square. I then clicked the little x. Then I hit Cmd-R again. Same error, but this time, I got a bigger stack trace.

![screen shot 2015-10-06 at 11 12 41 am](https://cloud.githubusercontent.com/assets/5479/10317832/2da3cb0e-6c1b-11e5-8e18-d1910baa7422.png)

**Comment by devoncarew** [comment]
Can you try running `.packages/sky/sky_tool install` from the CLI and see if the issue is that the APK is outdated on the device?

**Comment by sethladd** [comment]
My sky_tools wasn't updating, so it's very possible I had my plugin, local project, and globally activated packages all out of sync.

Closing this because I manually updated sky_tools. I'll keep an eye on it.
