### ISSUE TITLE
When running a Flutter app, displaying old logs is confusing

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#399]
I just learned that the logs visible in the console of the Atom runner aren't necessarily the logs from this most recent run. The current behavior is to show all logs from all time.

I would expect to only show logs from the point at which I've started my app. Is that possible?

Atom 1.0.19, dartlang 0.4.9, SDK 1.13.0-dev.2.0 running on macos.

**Comment by devoncarew** [comment]
We are passing in `--clear` to the sky_tool logs command:

https://github.com/dart-atom/dartlang/blob/master/lib/flutter/flutter_launch.dart#L98

@iansf, thoughts? The atom plugin is still using the python script - I didn't want to move over until after tomorrow.

**Comment by iansf** [comment]
On Seth's computer and device, directly running adb logcat -c was failing
to clear the logs (that's all sky_tool is doing), so I'm not immediately
sure what's going on right now.

**Comment by devoncarew** [comment]
> directly running adb logcat -c was failing to clear the logs

closing this as it seems to be an adb issues for one user. we can re-open if it seems more common
