### ISSUE TITLE
String literal highlighting goes haywire after seeing \\"

### ISSUE THREAD

**Issue by jamesr** [dart-atom/dartlang#418]
This code:

https://github.com/dart-lang/pub/blob/master/lib/src/package.dart#L256

duplicated here:

      files = files.map((file) {
        if (Platform.operatingSystem != 'windows') return "$dir/$file";
        return "$dir\\${file.replaceAll("/", "\\")}";
  

confuses the string literal syntax highlighter - it thinks the quote here continues onto the following lines.

**Comment by devoncarew** [comment]
<img width="574" alt="screen shot 2015-10-12 at 7 23 24 pm" src="https://cloud.githubusercontent.com/assets/1269969/10444071/c9c1dd14-7116-11e5-99d8-fa4781b35169.png">

It looks like it's breaking at `\\"`.
