### ISSUE TITLE
navigation to operator declaration does not work

### ISSUE THREAD

**Issue by yjbanov** [dart-atom/dartlang#424]
Examples:

In Dart Editor one used to be able to Cmd + Click (Ctrl + Click) on the characters underscored in the examples below and it would take you to the declaration, just like going to the declaration of a method/function does.

```dart
Zone.current['local'];
//          ^       ^
if (a == b) {
//    ^^
}
```

This does not work in Atom (although other kinds of navigation work).

**Comment by devoncarew** [comment]
@scheglov, is this supported by the analysis server? The atom handing code isn't special-casing based on the text under the click.

**Comment by scheglov** [comment]
Do you use `analysis.navigation` notification or `analysis.getNavigation` command?
The first definitely supports navigation to operators.
The second - not sure.

**Comment by devoncarew** [comment]
We're using the first. I'll try and repro and see if I can get more info.

**Comment by devoncarew** [comment]
@scheglov, I do not get any results back from the `getNavigation` command. Perhaps I'm not using it correctly.

However, when using the `navigation` event (which we're doing in the shipping app), I see results for positions 2 and 3 above. from looking at the returned nav event info, it looks like the right bracket has nav info, the `==`, but the left bracket has no associated nav info.

<img width="429" alt="screen shot 2015-10-21 at 11 01 57 pm" src="https://cloud.githubusercontent.com/assets/1269969/10658645/ac170440-784d-11e5-9105-c5e6b6ccaaca.png">

```dart
import 'dart:async';var bar = Zone.current['foo'];
dsdf() {
  String a = 'a';
  String b = 'b';
  return a == b;
}
```

**Comment by scheglov** [comment]
https://codereview.chromium.org/1402353009

**Comment by scheglov** [comment]
Fixed.
https://github.com/dart-lang/sdk/commit/289bd0a056abb17587a692fd9b1f5f02190139e5

**Comment by devoncarew** [comment]
@scheglov, thanks! Will close this since the fix will be in a future SDK rev.

**Comment by yjbanov** [comment]
:+1:
