### ISSUE TITLE
Extra outline view when using side-by-side (split) panes

### ISSUE THREAD

**Issue by alechenninger** [dart-atom/dartlang#428]
As in, View -> Panes -> Split right. I'm getting an extra outline view on the right side.

![screenshot from 2015-10-16 19-58-26](https://cloud.githubusercontent.com/assets/3496559/10555649/6e60cfac-7440-11e5-996e-f2be4aeef92e.png)

**Comment by devoncarew** [comment]
@alechenninger, thanks for the report. Can you include the plugin version that you're using?

I suspect that this may be another case of https://github.com/dart-atom/dartlang/issues/397. If you restart Atom, can you repro the issue?

**Comment by alechenninger** [comment]
I'm running 0.4.10. You might be onto something there, though. I did recently upgrade (can't remember if it was just before this issue happened, but it's plausible), and after restarting I can no longer reproduce.

**Comment by alechenninger** [comment]
When this did occur, It was only when two panes were open. If I closed one, only one one outline view remained, as expected. If I split again, the extra (erroneous) outline view reappeared.

**Comment by devoncarew** [comment]
Thanks for re-checking! We often have strange artifacts remaining when upgrading in place. Bits of the old plugin are still active. I can normally track this down to specific bugs, and fix those bugs, but new ones creep in. I think a more permanent solution would be to remove all listeners and DOM contributions automatically.

**Comment by devoncarew** [comment]
closing as stale; I think this may have been addressed by other changes
