### ISSUE TITLE
Should we move the button that fixes an issue, closer to the issue's message ?

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#433]
![screen shot 2015-10-19 at 4 05 48 pm](https://cloud.githubusercontent.com/assets/5479/10593780/51ff0f80-767b-11e5-8e31-09b985072355.png)

It's great that we prompt the user to run `pub get`. However, I wonder if we could make a stronger connection between "these problems HERE can be solved by doing this action HERE"

The UI as it is doesn't seem to indicate a connection between the "problems view" and the toast.

It might make more sense to help the user draw a connection: "we think these problems might be solved by running pub get. Run it now?"

**Comment by sethladd** [comment]
cc @lukechurch for any thoughts

**Comment by devoncarew** [comment]
Captured in #523
