### ISSUE TITLE
dartlang auto-indent gets confused by list literals

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-atom/dartlang#44]
```dart
List<String> = [
  "foo",
]
```

Hit enter after "foo",

Expect it to indent 2 spaces as per "foo".  Be sad that it indents 0 spaces.

Sky hits this a lot due to our new Widget(children: [ pattern where we list lots of child widgets on separate lines.

@devoncarew

**Comment by devoncarew** [comment]
Hmm, I'm seeing 0 spaces after the `[`, but am seeing 2 spaces after the `"foo",`. Not sure why what I'm seeing differs from what you're seeing. Can you attach a longer file, or link to a sky file where you see this behavior?

**Comment by devoncarew** [comment]
```
List<String> = [^
  "foo",^
]
```

With the recent PR, I'm now seeing 2 space indent when hitting return after the two carets above. We'll push out an update with the changes. @eseidelGoogle, can you re-open this if you're still seeing the issue, or open new issues w/ other indent problems? We can make some more changes via the editing regexs (https://github.com/dart-atom/dartlang/blob/master/settings/dart.cson#L4). Things that can't be handled via regex would require us to create a dynamic grammar file, which would be a few day effort.

**Comment by eseidelGoogle** [comment]
I just updated to 0.3.0 and tried:

```
List<String> = [
  'foo',
  'bar',
]
```

After [, it started a new line with 0 indent.

After ', it tried to insert 'var'. and then when I remove that, went to 0 indent.

Am I still behind in version?

**Comment by devoncarew** [comment]
We have to push out a `0.3.1` version w/ the fix - likely in a few hours :)
