### ISSUE TITLE
Duplicate priority files being set for active editors.

### ISSUE THREAD

**Issue by pq** [dart-atom/dartlang#446]
I'm seeing reliably lists of two repeated items.  For example, in the status page:
![screen shot 2015-10-23 at 1 59 30 pm](https://cloud.githubusercontent.com/assets/67586/10705474/f48279da-7992-11e5-84fc-9a71cf3eb909.png)
where I would expect 1 entry for each open file (or active editor).

(FWIW IDEA shows one for each open editor.)

I took a look at how focus changes are [tracking editors](https://github.com/dart-atom/dartlang/blob/master/lib/analysis_server.dart#L195) but nothing obvious is jumping out.

**Comment by devoncarew** [comment]
Cool. I'll try and repro. Turning the logging in atom all the way up, and watching the log in devtools, might pinpoint a culprit.

**Comment by devoncarew** [comment]
@pq, I'm unable to repro; I don't see dupes. Any ideas how it might have occurred, or what I could do to repro?

**Comment by devoncarew** [comment]
@pq, I'm going to close this based on my testing and the re-org of how we send in priority sources, but please re-open if you see it again.

**Comment by pq** [comment]
KK.  Thanks!
