### ISSUE TITLE
console view should hyperlink stacktraces

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#457]
<img width="913" alt="screen shot 2015-10-27 at 11 16 27 am" src="https://cloud.githubusercontent.com/assets/1269969/10768003/3cb7cdd4-7c9c-11e5-854a-3e47c872ff40.png">

**Comment by sethladd** [comment]
Can we do this in a generic way, or do we have to do something special for Flutter?

**Comment by devoncarew** [comment]
It can be generic - we'll recognize the stack trace line, and the launch type will handle resolving that to a source location.

**Comment by sethladd** [comment]
Very cool.

**Comment by sethladd** [comment]
Super cool, thanks!
