### ISSUE TITLE
support running on the mac with shells besides just bash

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#467]
like zsh :)

**Comment by devoncarew** [comment]
It looks like atom may be running in `bash` as is? And the launched processes seem to have the right path set up. So we may not need to do our bash trampolining thing.

**Comment by devoncarew** [comment]
Look into whether we can detect the current shell using `$SHELL`. If bash, just shell out. If zsh, the same. If csh, how do we detect which shell the user normally uses? (the Dock launches process in the csh, not whatever the user's default shell is)

**Comment by ianloic** [comment]
I have most of a patch working...
