### ISSUE TITLE
consider having some settings configured or configurable on a pre-project basis

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#48]
Related to https://github.com/dart-atom/dartlang/pull/46. Perhaps as a `.dart-project` file or similar.

**Comment by radicaled** [comment]
I think this comes up again in #57?

Maybe we should just do this on our end (defining a format, values, etc), and then when the analysis team is ready they can work backwards and implement the format and then we can drop our custom stuff?

**Comment by devoncarew** [comment]
Seems like we might have an atom specific file to identify which sub-dirs in a project are / aren't dart projects, and another file which configures the analysis (warnings to ignore?). The analysis ignore file would possibly be more applicable to other dart tooling environments as well.

Are there any conventions in atom as to where project config files / settings live? Like using a `.settings/` dir? Or just everything in the project root?

**Comment by devoncarew** [comment]
And, there _may_ be some clarity about analyzer ignore settings in the next day or so. I'll ping this thread if there are any updates.

**Comment by devoncarew** [comment]
In progress: https://github.com/dart-lang/sdk/issues/23851 :)

We can read from a file with this format; the analysis server will understand something substantially like that format shortly.

**Comment by devoncarew** [comment]
I think the `.analysis_options` file is gaining traction. I'll close this issue; we can revisit when analysis_options supports filtering warning types.
