### ISSUE TITLE
distracting "analyzing source..." message

### ISSUE THREAD

**Issue by jmesserly** [dart-atom/dartlang#481]
I've opened pkg/analyzer in the SDK repo. As I edit lib/src/generated/element.dart, I'm seeing a gear icon & "Analyzing source..." animate repeatedly in the lower right corner. This message is distracting, like an old school flash ad or something :). I don't think the message needs to appear... after all, if I'm typing, I expect analysis is just running in the background. One of the basic [UI design principles](https://en.wikipedia.org/wiki/Principles_of_user_interface_design) is to only show relevant info, without distracting info.

I'm using Atom 1.1.0, dartlang plugin at whatever version was currently on the package repository
(I followed these instructions: https://dart-atom.github.io/dartlang/)

**Comment by jmesserly** [comment]
Aside: other than that, it feels really fast! First impressions so far are that Atom Dart plugin is really nice :)

**Comment by devoncarew** [comment]
We debounce the AS analyzing messages a bit - I think we only show that gear if the analyzer has been working for 500ms. So, I think you're seeing abnormally long analysis tasks for just typing code. Agree that constant flashing would be distracting.

**Comment by devoncarew** [comment]
I'll verify the de-bounce min time and see if it seems reasonable.

**Comment by devoncarew** [comment]
It's 250ms right now: https://github.com/dart-atom/dartlang/blob/master/lib/analysis_server.dart#L364

**Comment by devoncarew** [comment]
Closing as I think https://github.com/dart-atom/dartlang/issues/493 is more specific. Please re-open if this is not the case -

**Comment by jmesserly** [comment]
ah good call. yeah I think that's the root cause of what I was seeing.
