### ISSUE TITLE
go to declaration not working?

### ISSUE THREAD

**Issue by jmesserly** [dart-atom/dartlang#482]
I tried cmd+click, but saw it was mapped to alt+click, similar to the hyperclick package:
https://github.com/dart-atom/dartlang/issues/26

but it doesn't seem to be working on my project (package:analyzer opened from SDK). I tried installing hyperclick too mentioned in that bug, but it didn't seem to help. Is there another package I should try and download?

Using: latest released dartlang + Atom 1.1.0

**Comment by jmesserly** [comment]
oh, I double checked, it's not just the alt+click -- right click+go to declaration isn't working for me either.

I do have some warnings in my project, but that shouldn't break it right?
With the exact same code open in IntelliJ, goto declaration is working.

BTW, does Atom use whatever Analysis Server I'm pointing my SDK at? Maybe I should try pointing it at a bleeding edge SDK build, might have some fixes

**Comment by devoncarew** [comment]
Yeah, atom will use the analysis server from the sdk. Something like SDK/bin/snapshots/analysis_server.snapshot.

To verify your SDK, you can use the 'show sdk info' command (from atom's command pallette). For a bit more analysis server diagnostics, you can use the 'analysis server status' command.

It sounds like there may be some config issue with the project, or general unhappiness? If hyperlink doesn't work it's probably a sign of larger analysis / config issues.

**Comment by jmesserly** [comment]
good news -- this seems to have went away after rebooting Atom! Maybe it doesn't work in the very first process -- which was also when my Dart plugin was installed.

**Comment by devoncarew** [comment]
I did find a recent regression - we weren't setting up analysis server file overlays for files open when atom started up. You would see this as a symptom - things like go to declaration not working. Closing and re-opening the file will work around the issue.

The fix for this will be in Monday's push -
