### ISSUE TITLE
breakpoints not getting hit?

### ISSUE THREAD

**Issue by jmesserly** [dart-atom/dartlang#487]
in package:analyzer, specifically
`test/generated/resolver_test.dart`

I went into StrongModeTypePropagationTest and added a new, failing test. I put a breakpoint on every line (with F9), then F5 to run in debug mode. Running works, and all tests pass except for that one failure. However, it never hit my breakpoint.

```
$ /Users/jmesserly/homebrew/opt/dart/libexec/bin/dart --version
Dart VM version: 1.13.0-dev.7.6 (Fri Oct 30 15:14:38 2015) on "macos_x64"
```
that's the Dart SDK Atom is pointing at.

**Comment by devoncarew** [comment]
Thanks for the report! Debugging is a few weeks away from being something we'd want to roll out to end-users. There's a way to turn it on - in your config.cson file, in the `dartlang` section, add `enableDebugging: true`. There will be issues :) We'll enable generally when it's more solid.

**Comment by jmesserly** [comment]
ah nice! yeah I see the issues, seemed like it failed to attach the first couple of times ("exited with code null"). But when I got it working it was pretty nice.

**Comment by devoncarew** [comment]
Closing; I'll add a UI checkbox to enable, with some disclaimer text about it being early days :)

**Comment by jmesserly** [comment]
Sounds good!
