### ISSUE TITLE
Putting Flutter options into their own menu under Packages?

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#492]
Right now, the only option under Packages is "Dart". Inside of that, there is a Flutter option.

Can we create a new Flutter top-level menu?

![screen shot 2015-11-05 at 11 24 59 am](https://cloud.githubusercontent.com/assets/5479/10979199/f6aa993c-83af-11e5-977e-0b448f89032f.png)

**Comment by devoncarew** [comment]
+1; the change would happen here https://github.com/dart-atom/dartlang/blob/master/menus/atom-dart.cson#L8
