### ISSUE TITLE
analysis server stuck in a loop

### ISSUE THREAD

**Issue by jmesserly** [dart-atom/dartlang#493]
What seems to be happening: analysis_server kicks off, finishes, then immediately goes from IDLE back to analyzing, even though I'm not typing or changing anything.

Here's the "finer" console log from a few seconds of it looping. 120MB(!)
https://drive.google.com/a/google.com/file/d/0B1F3uma0zu_xSGU5bkdOS01RdnM/view
$ dart --version
Dart VM version: 1.13.0-dev.7.6 (Fri Oct 30 15:14:38 2015) on "macos_x64"

atom version: 1.10
dart plugin version: 0.4.13

**Comment by devoncarew** [comment]
Thanks for the bug report! I'll have to create a new github label for bug reports greater than 100MB :)

The log contains responses from the AS to commands we're sending in. It doesn't contain the text for those commands however. I'll go over our logging code to make sure we're logging when we should. I suspect that those commands will be very interesting, either overlay changes, priority source changes, ...

The AS should not be causing re-analysis, but they'll probably want to know which commands are causing the re-analysis.

**Comment by devoncarew** [comment]
Hmm, we are logging commands to the server correctly, so I don't know why they're not showing up in your log.

**Comment by devoncarew** [comment]
We now trim very long messages from the AS when logging. The next version of the plugin should only create a log file ~200-300kb. Should be a lot easier for users and devs to dig through.

**Comment by devoncarew** [comment]
This issue was moved to dart-lang/sdk#24902

**Comment by devoncarew** [comment]
Hey @jmesserly, I moved this over to the sdk repo, so they'd have a tracking issue for the endless analysis.

**Comment by devoncarew** [comment]
@jmesserly, there's a change landing - https://github.com/dart-atom/dartlang/pull/688 - which might alleviate this a bit. This new build should be available tomorrow.

**Comment by jmesserly** [comment]
Awesome!
