### ISSUE TITLE
Completion ordering for library imports is very incorrect

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#5]
(was https://github.com/dart-lang/atom-dartlang-experimental/issues/94)

```
import 'dart:io' as io;
io.
```

I don't think that 'BytesBuilders' is the most commonly used class from the static list, or is the right lexical ordering.

I think the problem is that we're not lexically sorting for items of the same level of priority from Analysis Server

**Comment by devoncarew** [comment]
@lukechurch, we're sorting the returned completions first by relevance, and then by case-insensitive lexical order on the completion text.
