### ISSUE TITLE
Clickable exceptions

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#508]
Would love to be able to click a source location in an exception and jump to that location.

For example:

![screen shot 2015-11-10 at 3 05 07 pm](https://cloud.githubusercontent.com/assets/5479/11078710/83be647e-87bc-11e5-8c43-6a9f9aee987a.png)

Atom 1.1.0, dartlang 0.4.14, SDK 1.13.0-dev.7.10 running on macos.

**Comment by devoncarew** [comment]
+1! Tracking it here: https://github.com/dart-atom/dartlang/issues/457
