### ISSUE TITLE
How do I run a Flutter app with checked mode / not checked mode?

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#513]
I'm using Cmd-R which is great, but I don't know if checked mode is on or off, and I don't know how to configure it for a run.

Thanks for your help!

**Comment by devoncarew** [comment]
We need to add support for this; this'll come as part of the work to have a UI to configure launch configurations.

**Comment by sethladd** [comment]
If that UI is a long ways away, maybe a new keyboard shortcut? Cmd-Option-R ?
