### ISSUE TITLE
SDK version check warns about -edge versions needlessly

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-atom/dartlang#515]
SDK version 1.12.0-edge.13a372eca09d01941c6c520b3b7ea18200fb5658 is older than the recommended version of 1.12.0. Please visit www.dartlang.org to download a recent SDK.

This was added in #343 (which is awesome!) but it doesn't need to warn me about edge versions.

Maybe the semantic versioning isn't quite right here?  Maybe it needs to be +edge instead of -edge?
http://semver.org/spec/v2.0.0-rc.1.html

I suspect that Dart has some built in ability to compare semantic versions that @devoncarew used here?

**Comment by devoncarew** [comment]
Yeah, I'm using a semantic compare, but I think technically `1.12.0-foo` < `1.12.0`.

If we want to special case edge versions we can.

But you'll probably want to upgrade to 1.12.0 stable, and more likely a 1.13.0 dev release :)

**Comment by eseidelGoogle** [comment]
Ah.  Atom was pointed at an old Dart. :(

**Comment by eseidelGoogle** [comment]
mb.

**Comment by eseidelGoogle** [comment]
I would have been slightly less confused if the warning had included the path to the SDK it was using.  But this was also just user error on my part.  Turns out I was pointing at an old SDK.

**Comment by devoncarew** [comment]
It's easy enough to show the path as well, and it will help users figure out where the old version is coming from.
