### ISSUE TITLE
Unclear how to open Observatory from Atom

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#521]
I right-clicked in my main.dart.

I right-clicked on my main.dart.

I looked in the setting of my Dartlang plugin.

I checked https://dart-atom.github.io/dartlang/

I could be missing how to open Observatory, assuming I just ran an app, or maybe we don't have a way to do it?

Thanks!

**Comment by sethladd** [comment]
For those following along, the quick workaround is to launch your app with Atom, and then open a browser tab and go to `http://localhost:8181`

**Comment by devoncarew** [comment]
fixed:
<img width="350" alt="screen shot 2015-11-23 at 2 33 28 am" src="https://cloud.githubusercontent.com/assets/1269969/11334543/9bd0f0fe-918a-11e5-9380-b59f54bb4c1f.png">

**Comment by sethladd** [comment]
Cool, thanks!
