### ISSUE TITLE
Flutter: F5 fails because "adb" not found in $PATH.

### ISSUE THREAD

**Issue by DavidMihola** [dart-atom/dartlang#528]
There must be something wrong with my dart-atom setup.

I've been using this machine for more than a year of "regular" Android development.

Also:

    dmta@elite:~/flutter$ echo $PATH
    /home/dmta/.pub-cache/bin:/home/dmta/bin/dart-sdk/bin:/home/dmta/bin/apache-maven-3.3.3/bin:/home/dmta/bin/activator-1.3.5-minimal:/home/dmta/development/android-sdk-linux/tools:/home/dmta/development/android-sdk-linux/platform-tools:/home/dmta/development/android-sdk-linux/build-tools/21.1.0:/home/dmta/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
    dmta@elite:~/flutter$ echo $ANDROID_HOME
    /home/dmta/development/android-sdk-linux
    dmta@elite:~/flutter$ which adb
    /home/dmta/development/android-sdk-linux/platform-tools/adb

So, the directory containing the `adb` executable is included in `$PATH` and `$ANDROID_HOME` is pointing to the the SDK folder. And finally `which adb` produces the correct executable path.

I am new to both Atom and Dart/Flutter - what am I doing wrong here?

**Comment by devoncarew** [comment]
Sounds like a path issue. Can you confirm that you're running on linux? Also, this info would help:

- the shell you're using (bash, ...)
- the version of dart (dart --version)
- whether you're starting atom up from the command-line or a gui launcher (like the mac's Dock)

**Comment by DavidMihola** [comment]
Hello,

* Linux: Yes, Ubuntu, to be precise.
* Shell: bash
* Dart: Dart VM version: 1.12.2 (Wed Oct 21 07:18:28 2015) on "linux_x64"
* Run how: Running through gnome-launcher (but not within Gnome but within xmonad).

**But:** When I run `atom` from bash everything works fine! Sorry for not thinking of this myself!

**Comment by devoncarew** [comment]
I think what's happening is that that launcher (`gnome-launcher`) is not starting the atom process in the bash shell, or not passing in the env variables from your init script. Either way `$PATH` is not getting set up correctly, and the processes that Atom launches will not have your path setting. Not sure what the best resolution is here...

**Comment by DavidMihola** [comment]
I'm fine with just running `atom` from a shell - it seems that environment variables not being available  to processes launched through `gnome-launcher` is a more general problem and not related to Atom at all...

**Comment by devoncarew** [comment]
Cool; thanks again for the reports.
