### ISSUE TITLE
Creating Flutter Project: ProcessException: No such file or directory

### ISSUE THREAD

**Issue by DavidMihola** [dart-atom/dartlang#529]
After creating a new Flutter project I always get the following error:

    Creating spring_queen_0369...
    /home/dmta/flutter/spring_queen_0369/.gitignore
    /home/dmta/flutter/spring_queen_0369/pubspec.yaml
    /home/dmta/flutter/spring_queen_0369/README.md
    /home/dmta/flutter/spring_queen_0369/lib/main.dart 
    Running pub get...
    ProcessException: No such file or directory
      Command: pub get
    Exception:
    dart:io                                                         Process.start
    package:sky_tools/src/commands/init.dart 48                     InitCommand.run.<async>
    dart:async                                                      Future.Future.microtask
    package:sky_tools/src/commands/init.dart                        InitCommand.run
    package:args/command_runner.dart 178                            CommandRunner.runCommand.<fn>
    dart:async                                                      Future.Future.sync
    package:args/command_runner.dart 131                            CommandRunner.runCommand
    package:sky_tools/src/commands/flutter_command_runner.dart 108  FlutterCommandRunner.runCommand
    package:args/command_runner.dart 105                            CommandRunner.run.<fn>
    dart:async                                                      Future.Future.sync
    package:args/command_runner.dart 105                            CommandRunner.run
    package:sky_tools/executable.dart 60                            main.<async>.<fn>.<async>
    package:stack_trace                                             Chain.capture
    package:sky_tools/executable.dart 59                            main.<async>

in a red box in the top right corner of the screen.

And below that a blue box saying:

    Pub has never been run for project spring_queen_0369/. Run 'pub get'?

And when I click `Run pub...` it always works...

So, is there something wrong with my setup, preventing the red box from finding the `pub` executable?

**Comment by devoncarew** [comment]
I'm not sure exactly what's going on here, but it does look path related.

In the first case, atom is able to launch the `flutter` process. That process is not able to launch `pub` however. So the `flutter` process for some reason didn't get your system PATH setting.

For the 2nd case, we execute the pub tool out of the sdk directly. So it's not dependent on a path setting.

**Comment by DavidMihola** [comment]
Like in #528 starting `atom` from bash resolved the problem!

Sorry again!

**Comment by devoncarew** [comment]
I'll close this and keep the other open. Thanks for the reports!
