### ISSUE TITLE
default jump-to-declaration keyboard shortcut conflict with intel graphic driver

### ISSUE THREAD

**Issue by rinick** [dart-atom/dartlang#532]
`jump-to-declaration` is using `ctrl-alt-down`, 
when use that in windows, this will be captured by intel graphic driver and causes it to rotate the screen.

I can turn off the keyboard shortcut from the graphic setting, but since intel graphic diver is installed on almost every windows laptop, it's probably better to use a different shortcut for this feature.

**Comment by devoncarew** [comment]
Updated - thanks for the report!
