### ISSUE TITLE
Show code comments when hovering over symbols and also in auto-complete box

### ISSUE THREAD

**Issue by aghassemi** [dart-atom/dartlang#539]
It would be great if code comments are displayed when developers hover over symbols. 

Also showing 1-2 lines of code comments in the auto-complete box would be very useful.

@sethladd 

Atom 1.0.19, dartlang 0.4.15, SDK 1.13.0-dev.5.0 running on linux.

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by devoncarew** [comment]
Comments now show up in the auto-complete dialog, courtesy of analysis server changes and https://github.com/dart-atom/dartlang/pull/674.

**Comment by devoncarew** [comment]
I'm closing the remaining half of this in favor of https://github.com/dart-atom/dartlang/issues/7; thanks for the report!
