### ISSUE TITLE
Sync the tree to the current file

### ISSUE THREAD

**Issue by tvolkert** [dart-atom/dartlang#546]
It's good that the navigation tree highlights the current file when you switch tabs between your various project files.  But it doesn't expand the tree as necessary to expose the current file in the tree if it's not already exposed.  This becomes a nuisance when hyperlinking to source code that's in an external package, or dart SDK code.

Atom 1.0.19, dartlang 0.4.14, SDK 1.13.0-dev.6.0 running on linux.

**Comment by devoncarew** [comment]
I have not tried it, but the atom `synced-sidebar` package might be a solution here.

**Comment by devoncarew** [comment]
I've been using `synced-sidebar` for a while now - it's working great. I'm going to update the docs to recommend it. Thanks for opening the issue!

**Comment by devoncarew** [comment]
http://dart-atom.github.io/dartlang/#install
