### ISSUE TITLE
Jump back and forth between navigations

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#55]
One thing I really miss from IDEs is a keyboard shortcut to jump back and forth in code navigations.

For example:

* jump to definition with the mouse
* jump back to previous location with a keyboard

In WebStorm, it was `Cmd-[` if I remember correctly.

**Comment by sethladd** [comment]
I'm really missing this. A lot of "jump to definition" leads me to want to "jump back" to my previous location.

**Comment by sethladd** [comment]
For anyone following along, this might help: https://atom.io/packages/last-cursor-position

**Comment by devoncarew** [comment]
I'm going to close this as resolved, but we should plan to add `last-cursor-position` to a getting started / how to get set up doc.

**Comment by sethladd** [comment]
sgtm!
