### ISSUE TITLE
Warnings are more visually salient than errors

### ISSUE THREAD

**Issue by lukechurch** [dart-atom/dartlang#564]
![image](https://cloud.githubusercontent.com/assets/2978182/11319923/a71e77de-9080-11e5-9f33-939c701e4773.png)

The warnings are are more salient than the errors, due to their lighter background colour.

Consider using a more substantially different hue (more orange/yellowy) and matching the saturation and lightness to the red. This will make them more easily distinguishable but without hiding the errors behind the warnings. You might well need to brighten up the red a bit at the same time to make this more pleasant as a scheme.

**Comment by devoncarew** [comment]
@lukechurch, these colors are specified by the theme. We can create our own recommended theme but I'm not sure it's worth the effort. If we use our own colors for error/warning/info, they're not guaranteed to work well with the other theme colors, like the background color of the text foreground color. We could get some serious contrast errors, where the text wasn't readable.
