### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by mnordine** [dart-atom/dartlang#565]
Does debugging work yet?
I created a new project, set a breakpoint, then do Debug Run, but the breakpoint doesn't get hit.

**Comment by devoncarew** [comment]
Yeah, it's not functional yet. I'll ping this issue when there's something to try.

**Comment by kasperpeulen** [comment]
@devoncarew Is debugging support purely for flutter, or could it also work for console/web apps?

**Comment by devoncarew** [comment]
It'll work for console apps as well - flutter and console apps use the same protocol. Web apps would be a totally different ball of wax.

**Comment by devoncarew** [comment]
Turned on by default here: https://github.com/dart-atom/dartlang/pull/651
