### ISSUE TITLE
Unclear how to view the output of `flutter logs` after a Cmd-R

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#575]
I've just started a new Flutter run with Cmd-R, and I see this:

```
[myapp/] flutter start
Installing SkyShell.apk on device.
android: --------- beginning of main
android: --------- beginning of system
```

It's unclear if I'm viewing the output of `flutter logs` or not? The reason is, I see `flutter start` there, but I don't see `flutter logs`, and I'm left wondering if I'm missing info I should be seeing.

I *think* I'm looking at logs output. If displaying the logs output is the default for `flutter start`, let's close this issue (user education error). If we're doing a little bit of magic, let's display something like "Displaying logs"

Atom 1.2.2, dartlang 0.4.15, SDK 1.13.0 running on macos.

**Comment by devoncarew** [comment]
Yeah, atom invokes `flutter start`, write all it's stdio to the console, waits for it to finish, then invokes `flutter logs` and appends its stdio to the console. So you're seeing the results of invoking flutter start and flutter logs in sequence.

**Comment by sethladd** [comment]
Can we display `flutter logs` or some other hint?

Or, don't display `flutter start`.

It's a two step process on the command line, which is why I was confused.

**Comment by devoncarew** [comment]
Fixed in https://github.com/dart-atom/dartlang/pull/582 - we now show the `flutter logs` command text when starting.
