### ISSUE TITLE
Cmd-R doesn't work when viewing a launch config

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#577]
Open a launch config file.
Type Cmd-R

Expected: launch/run the app
Actual: Opens this:

![screen shot 2015-11-24 at 1 48 26 pm](https://cloud.githubusercontent.com/assets/5479/11381648/0f462482-92b2-11e5-9bdf-de3d48544fa8.png)

Atom 1.2.4, dartlang 0.4.15, SDK 1.13.0 running on macos.

**Comment by devoncarew** [comment]
Fixed in https://github.com/dart-atom/dartlang/pull/574 (it would be great to get this out in a release).

**Comment by sethladd** [comment]
Ah, thanks! Let's do a release first thing next week.
