### ISSUE TITLE
Requesting ability to choose which device to run Flutter app on

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#579]
If I have both an emulator running, and a physical device plugged in, and try to run my Flutter app, I get:

```
[myapp/] flutter start
Warning: Multiple Android devices are connected, but no device ID was specified.
severe: Unable to run application - no connected devices.
• exited with code 2 •
```

Could we as the user which device they want to run on?

Atom 1.2.4, dartlang 0.4.15, SDK 1.13.0 running on macos.

**Comment by devoncarew** [comment]
fixed by https://github.com/dart-atom/dartlang/pull/756 for the UI; the cli tool recently got a `-d` flag to select the device as well
