### ISSUE TITLE
Can't copy and paste analyzer stack trace from dialog

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#587]
Atom 1.2.0 dartlang 0.4.15

While attempting to find references to a named constructor, a red dialog box appeared showing an Analyzer stack trace. Unfortunately this dialog doesn't support copy and paste, so here's a summary:

```
method: search.findElementReferences, id: 177
The null object does not have a getter 'constructors'
IndexableElementKind.forElement indexable_element.dart:166
IndexableElement.kind
ElementCode.encodeHash code.dart:126
SplitIndexStore.getRelationships split_store.dart:880
...
ElementReferencesComputer._findSingleElementReferences
```

(Reanalyzing sources fixed it.)

**Comment by devoncarew** [comment]
@skybrian, can you repost this to to the sdk repo, or use the github repo issue mover?

The copy and paste issue is a problem with core atom. I'll open a bug for them if there's not one already. We've implemented our own fixes for the errors and console views.
