### ISSUE TITLE
No Settings button immediately after install

### ISSUE THREAD

**Issue by johnmccutchan** [dart-atom/dartlang#60]
Immediately after installing the package I do not see a Settings button. See screenshot.

Restarting Atom fixes this.

I installed emmet, linter, and dartlang. Then I navigated from Install to Packages. Then I took the screenshot.

<img width="1024" alt="no dartlang settings button immediately after install" src="https://cloud.githubusercontent.com/assets/224266/8689495/256a543a-2a5d-11e5-9d61-031330660a05.png">

**Comment by devoncarew** [comment]
This is a bug in atom's settings page. I'm going to close this as it's non-critical; I don't see a corresponding issue in the [settings view](https://github.com/atom/settings-view/issues) repo.
