### ISSUE TITLE
Code formating in doc popup is incorrect

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#62]
![screen shot 2015-07-14 at 8 23 55 pm](https://cloud.githubusercontent.com/assets/5479/8690219/636f144c-2a66-11e5-9823-b96ec6b95eb0.png)

Maybe we're not translating newlines and breaks correctly?

**Comment by devoncarew** [comment]
This UI will go away in a few days -

**Comment by devoncarew** [comment]
Done: https://github.com/dart-atom/dartlang/pull/84
