### ISSUE TITLE
Set breakpoint, restarted app, app didn't stop at breakpoint

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#626]
Using version 0.4.17 and the starter app from Flutter.

I set the breakpoint here:

![screen shot 2015-12-08 at 1 50 23 pm](https://cloud.githubusercontent.com/assets/5479/11669635/a4127fba-9db2-11e5-9e3c-93f428d7f455.png)

**Comment by devoncarew** [comment]
Can you re-test w/ the latest debugger?

**Comment by sethladd** [comment]
Still doesn't work (after I restarted Atom).

**Comment by sethladd** [comment]
Still happening (I'm on 0.5)

**Comment by devoncarew** [comment]
I think this is fixed.
