### ISSUE TITLE
Missing the Observatory button

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#643]
I thought we had a button to open the Observatory?

![screen shot 2015-12-11 at 3 39 44 pm](https://cloud.githubusercontent.com/assets/5479/11758229/777850fc-a01d-11e5-9809-16795478ecdb.png)

Atom 1.2.4, dartlang 0.4.17, SDK 1.14.0-dev.1.0 running on macos.

**Comment by devoncarew** [comment]
Regressed as part of a refactoring; fixed in https://github.com/dart-atom/dartlang/pull/637.
