### ISSUE TITLE
Relative paths not resolving

### ISSUE THREAD

**Issue by appsforartists** [dart-atom/dartlang#650]
In [this repo](https://github.com/flutter/experimental-flux/blob/bbd4f669321e7f2d94c82d962f37916d228ee3eb/lib/main.dart#L4-L6), relative imports like:

```dart
import './components/ShoppingList.dart';
```

are raising errors:

```
Target of URI does not exist: './components/ShoppingList.dart'   lib/main.dart, line 5
```

However, the paths are correct (they even show up in autocomplete) and the app runs fine in Flutter.

**Comment by devoncarew** [comment]
Hmm, this is working for me (on macos, dart 1.14.0-dev.4.0). I needed to change the name of the package slightly to get pub to run. I do see one issue:

```
warning] Undefined name 'lineThrough' (experimental-flux/lib/components/shopping_list_item.dart, line 23, col 46)
1 warning found.
```

but for me, the relative paths resolve, both with the command-line `dartanalyzer` and using Atom.

**Comment by appsforartists** [comment]
I updated to .5 and it seems to be working now.  Will reopen if I reencounter.
