### ISSUE TITLE
Double-click in gutter to set breakpoint

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#654]
It doesn't appear that I can do this.

**Comment by sethladd** [comment]
Discoverability of how to set a breakpoint is low. Right-clicking in various locations in the UI didn't show me how to set the breakpoint :(

**Comment by devoncarew** [comment]
Just F9 for now, but clicking in the gutter and right-clicking in the editor should both be added.

**Comment by ltackmann** [comment]
+1, atlas document it on the frontpage of the plugins web page. The ability to debug a web app decently is a major win for Dart.

**Comment by sethladd** [comment]
woohoo!
