### ISSUE TITLE
Formatting command keybinding clashes with Atom's project find keybinding

### ISSUE THREAD

**Issue by austincummings** [dart-atom/dartlang#66]
I think it's best not to break default functionality. A better keybinding might be `ctrl-alt-b`, this is what the [atom-beautify](https://atom.io/packages/atom-beautify) package uses by default.

**Comment by devoncarew** [comment]
Feel free to change w/ a PR. cmd-shift-f is what I'm used to w/ Eclipse, but I agree that we shouldn't intentionally conflict with default keybindings.
