### ISSUE TITLE
superMixin support should not be enabled by default

### ISSUE THREAD

**Issue by danrubel** [dart-atom/dartlang#677]
There is a test to ensure that superMixin support can be enabled and disabled. Both the [enable and disable tests](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/test/integration/analysis/error_test.dart#L39) pass. This feature should be disabled by default, yet when I paste the sample code from the ["disable superMixin support" test](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/test/integration/analysis/error_test.dart#L39) in a dart file, I don't see any errors/warnings from analysis server.

```
class Test extends Object with C {
  void foo() {}
}
abstract class B {
  void foo();
}
abstract class C extends B {
  void bar() {
    super.foo();
  }
}
```

Apparently enableSuperMixin is hardcoded true in the Atom codebase.

**Comment by devoncarew** [comment]
Is this causing issues for you? This is something that was requested by the Flutter team.

**Comment by danrubel** [comment]
It no longer needs to be hard coded true, because analysis server correctly checks the both .analysis_options file (https://github.com/dart-lang/sdk/issues/24750) and _embedder.yaml file (https://github.com/dart-lang/sdk/issues/24733). I verified that you can have a non-flutter and flutter project co-exist with correct errors/warnings in both. I'll have a tiny dartlang patch for this shortly.
