### ISSUE TITLE
analysis server dies on startup for second window

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#682]
The exception is: "Uncaught Error: This socket has been ended by the other party"

Workaround: uncheck "Start the analysis server with debug flags" in settings.

**Comment by devoncarew** [comment]
I can repro this. I had though the analysis server had been hardened against this specific issue.

@bwilkerson

**Comment by devoncarew** [comment]
Thanks for the report! Closing in favor of https://github.com/dart-lang/sdk/issues/25394.

My preference though would be to be able to open the diagnostics port via an API call, and have it return the port that it bound to. Having to use a CLI flag means that at a minimum the analysis server has to be restarted to change the preference, if not all of atom.
