### ISSUE TITLE
Debugging doesn't work on code, unless that code is run 2-3 seconds after app starts

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#689]
_From @sethladd on January 12, 2016 16:58_

_Copied from original issue: flutter/atom-flutter#30_

**Comment by devoncarew** [comment]
This is flutter specific.

**Comment by devoncarew** [comment]
We need to pass `--pause_isolates_on_start=true` through flutter start to the VM. We can look at how `--checked` works - it needs to do the same thing.

**Comment by devoncarew** [comment]
Tracked in the flutter repo (and in progress).

**Comment by sethladd** [comment]
Thanks for the update!
