### ISSUE TITLE
Sample app is not starting

### ISSUE THREAD

**Issue by nalkon** [dart-atom/dartlang#690]
I just cloned the newest version of Flutter, but something is wrong:
1. It seems the version is kind of old: commands "flutter  --version" and "flutter upgrade" don't work.  Error: "Could not find a command named "upgrade"." and "Could not find an option named "version"."
2. After creating sample app my_app  (according to the instructions in Getting Started Guide), "flutter start" command results in the following error:

Invalid argument(s): join("packages/sky_tools/cache", "sky_engine", null, "Release", "linux-x64"): part 2 was null, but part 3 was not.

Exception:
package:path/src/context.dart 572                               _validateArgList
package:path/src/context.dart 210                               Context.join
package:path/path.dart 225                                      join
package:sky_tools/src/artifacts.dart 205                        ArtifactStore._getCacheDirForArtifact
package:sky_tools/src/artifacts.dart 213                        ArtifactStore.getPath.<async>
dart:async                                                      _Completer.completeError
package:sky_tools/src/artifacts.dart 227                        ArtifactStore.getPath.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/artifacts.dart                            ArtifactStore.getPath
package:sky_tools/src/toolchain.dart 36                         _getCompilerPath.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/toolchain.dart                            _getCompilerPath
package:sky_tools/src/toolchain.dart 46                         Toolchain.forConfigs.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/toolchain.dart                            Toolchain.forConfigs
package:sky_tools/src/commands/flutter_command.dart 28          FlutterCommand.downloadToolchain.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/commands/flutter_command.dart             FlutterCommand.downloadToolchain
package:sky_tools/src/commands/start.dart 48                    StartCommand.runInProject.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/commands/start.dart                       StartCommand.runInProject
package:sky_tools/src/commands/flutter_command.dart 56          FlutterCommand.run.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/commands/flutter_command.dart             FlutterCommand.run
package:args/command_runner.dart 178                            CommandRunner.runCommand.<fn>
dart:async                                                      Future.Future.sync
package:args/command_runner.dart 131                            CommandRunner.runCommand
package:sky_tools/src/commands/flutter_command_runner.dart 108  FlutterCommandRunner.runCommand
package:args/command_runner.dart 105                            CommandRunner.run.<fn>
dart:async                                                      Future.Future.sync
package:args/command_runner.dart 105                            CommandRunner.run
package:sky_tools/executable.dart 60                            main.<async>.<fn>.<async>
package:stack_trace                                             Chain.capture
package:sky_tools/executable.dart 59                            main.<async>

My OS: Ubuntu 14.04, 64 bit
Android phone: Nexus 5
Android version: 6.0
Dart version: 1.13.2

**Comment by nalkon** [comment]
Ok, I figured out the problem. It was old .pub_cache directory. Probably from the previous install. After I deleted it, everything started to work properly.

**Comment by devoncarew** [comment]
Can you make sure that are are running the `flutter` command from the repo you cloned, and not an older one from a pub activation? I'd verify which flutter is being picked up from your path, and run the `pub global deactivate flutter` command as well, just to be safe.

**Comment by devoncarew** [comment]
Ah, just saw you message. Glad it's working now.
