### ISSUE TITLE
getting started: after a new flutter app is created, then what?

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#695]
After having run through various getting started flows, the ones that make it really easy are the ones that make it obvious how to run your first app.

The "create a new flutter app" flow is good, I end up with a working Flutter app. yay!

But, for the new user, it's not obvious how to run this. Some ideas:

* display connected devices
* make it clear that I can run an app on those connected devices
* for the first-time user, show a info toast that says "We see you have a device connected. Hit Cmd-R to run this app now!"

Thanks for your thoughts!

Atom 1.3.3, dartlang 0.5.1, SDK 1.13.1 running on macos.

**Comment by devoncarew** [comment]
fixed by https://github.com/dart-atom/dartlang/pull/756
