### ISSUE TITLE
0.5.3 warns about undefined lint rules

### ISSUE THREAD

**Issue by ThomasLocke** [dart-atom/dartlang#711]
dartlang version: 0.5.3
Atom version: 1.3.2
System: Slackware 14.1 x64

Supported lint rules are: https://dart-lang.github.io/linter/lints/

The dartlang plugin warns/complains about two of those rules:

- always_declare_return_types
- always_specify_types

Actually I'm not sure it is the dartlang plugin that is emitting the warnings, and neither am I sure that the above posted lint rules are globally accepted as valid. These are just wild assumptions made by me.

**Comment by devoncarew** [comment]
Do you have an `.analysis_options` files for the project? I believe that file is used to enabled and disable specific lints.

**Comment by ThomasLocke** [comment]
It is on that file that the warnings are shown.

analyzer:
  strong-mode: true
linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - camel_case_types
    - constant_identifier_names
    - empty_constructor_bodies
    - library_names
    - non_constant_identifier_names

**Comment by kasperpeulen** [comment]
Which version of Dart are you using?

I believe it is only fully supporting in dev channel (1.14-dev.xx).
And not in the stable channel (1.13.2)

**Comment by ThomasLocke** [comment]
I'm on stable, so that might be it.

**Comment by devoncarew** [comment]
Cool. Adding @pq to confirm, but that sounds like the issue.

**Comment by pq** [comment]
> Adding @pq to confirm, but that sounds like the issue.

:+1: spot on.
