### ISSUE TITLE
renaming with split window causes Atom to hang

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#716]
Using Atom 1.3.2 on a Mac:

- Open a Dart file.
- Right-click on the tab and choose "Split right"
- Rename a Dart variable.

This causes Atom to hang. Eventually I get a "the application is not responding" dialog.

I found that upgrading to Atom 1.4 fixed this issue.

**Comment by skybrian** [comment]
Possibly relevant: I have autoformat on save turned on.

**Comment by devoncarew** [comment]
Hmm, I can repro this in atom 1.3.1, but not in atom 1.4.

**Comment by skybrian** [comment]
Yes, that's right.

**Comment by devoncarew** [comment]
Yeah, I think this is uncovering a bug on the `atom.workspace.open()` call. Atom is not returning from that call when I have two panes open during a refactoring. I've worked around a bug in this API call before. Looks like this particular issue is fixed in 1.4.

**Comment by devoncarew** [comment]
I'm going to close this out as atom 1.4 is now the stable version.
