### ISSUE TITLE
Uncaught errors keep popping up after I stopped and started analyzer

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#72]
I noticed analyzer was stuck just running.
I clicked "stop", and then "start".
Now, I'm getting unlimited "Uncaught errors"...

![screen shot 2015-07-16 at 10 39 46 am](https://cloud.githubusercontent.com/assets/5479/8730678/24fa9208-2ba7-11e5-87b2-c339b5535cdf.png)

And, looks like analyzer is stuck in "shutdown", even after I clicked "Start"

FWIW my CPU is not at 100%.

**Comment by devoncarew** [comment]
This one was addressed a few days ago in https://github.com/dart-atom/dartlang/pull/54, but we haven't pushed a new version since. @sethladd, do you mind reving the version and changelog and pushing that?
