### ISSUE TITLE
Robustness: Heathchecks and restarts for analyzer

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#73]
If analyzer gets stuck, let's restart it for our users.

Might need something like a health check and heuristics for "analyzer is dead, jim" and restart.

Users shouldn't have to diagnose why their editor is slow or broken. :)

**Comment by sethladd** [comment]
Might fix issues like https://github.com/dart-atom/dartlang/issues/72

**Comment by devoncarew** [comment]
We have some diagnostics plumbed in.
