### ISSUE TITLE
wait for an isolate runnable event before setting any breakpoints

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#736]
From https://github.com/dart-lang/sdk/issues/25602.

**Comment by johnmccutchan** [comment]
@turnidge FYI

**Comment by devoncarew** [comment]
@johnmccutchan @turnidge, how do I know the state of a particular isolate? When I connect, I get the list of currently known isolate (`getVM().isolates`). I then respond to events about new isolates (`kIsolateStart` -> `kIsolateRunnable` -> [`kIsolateUpdate` ->] `kIsolateExit`). But if an isolate existed before I first connected, how to I know whether that isolate is at the started state or the runnable state?

**Comment by johnmccutchan** [comment]
@devoncarew Good catch. I've got a CL out and a fix will be merged in to stable for 1.4.1 that adds a 'runnable' bit.

**Comment by johnmccutchan** [comment]
Fixed in 1e6c5f196befa21b26b3bd40877167691ee9c346. An Isolate has a "runnable" boolean property.

**Comment by johnmccutchan** [comment]
Merge request for stable https://github.com/dart-lang/sdk/issues/25721

**Comment by devoncarew** [comment]
Thanks! Will update and use a `runnable` flag if one is present.

**Comment by johnmccutchan** [comment]
@devoncarew You should probably let the user know if the protocol version < 3.2 that debugging won't work.
