### ISSUE TITLE
Missing Getting Started Guide

### ISSUE THREAD

**Issue by paulb777** [dart-atom/dartlang#750]
There is no guide at the "getting started guide" link at [https://atom.io/packages/dartlang]. It links to a page(](https://dart-atom.github.io/dartlang/])) with a link to the github page and the issues page.

**Comment by devoncarew** [comment]
Thanks for the report! It look like this issue: https://github.com/t413/SinglePaged/issues/35. The jekyll theme we're using isn't compatible with jekyll 3.0, which github just switched too.

**Comment by devoncarew** [comment]
Fixed (https://github.com/dart-atom/dartlang/commit/caa49dfb501e4950e223a5e0d4feb3853d172011)! Thanks for letting us know.

http://dart-atom.github.io/dartlang/
