### ISSUE TITLE
don't set analysis roots automatically unless top-level directory is a Dart package

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#762]
When you open a directory in Atom, the dartlang plugin automatically sends that directory to the Analysis Server. The Analysis Server then recursively searches for Dart packages and starts analyzing all of them.

This seems like bad behavior. For example, when I open the Dart SDK working directory in Atom, I don't actually want to analyze every Dart package in the SDK.

It seems like instead, we should send the top-level directory automatically only if it has a pubspec.yaml file or .analysis_options file. When opening a .dart file, Atom should search for the closest ancestor directory with a pubspec.yaml or .analysis_options file and make that a new analysis root. This should make Atom more practical to use with large directory trees that have multiple Dart projects.

**Comment by devoncarew** [comment]
We do this now. The atom plugin scans recursively for dart projects from the roots (w/ a cut-off depth of 3 levels). We then pass located dart projects to the analysis server as roots; it will scan those for nested dart projects.

This technique doesn't cover all possible use cases, but it is simple, and does cover many of them.

**Comment by skybrian** [comment]
Confirmed. Sorry about that!
