### ISSUE TITLE
Cleared log output is shown at each launch

### ISSUE THREAD

**Issue by johnmccutchan** [dart-atom/dartlang#775]
1) Run an Android Flutter app.
2) Clear the console.
3) Run the app again and you will see the old cleared console log messages repeated.

**Comment by devoncarew** [comment]
The clear button's functionality was confusing; removed in https://github.com/dart-atom/dartlang/pull/784. There is an open issue (tracked in the flutter repo) where we have trouble clearing the adb logcat buffer before a run.
