### ISSUE TITLE
add a setting to hide the new toolbar

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#778]
Most of the buttons are disabled for me except for toggle outline view. Perhaps it requires flutter? Maybe it shouldn't be shown except for flutter projects?

**Comment by devoncarew** [comment]
The next version will hide the device pulldown exception for flutter projects. The app pulldown should be relevant for all dart projects. We'll iterate on the UX a bit though, as there are known rough spots w/ this first cut.

You can hide the toolbar from the settings for the `atom-toolbar` plugin (also togglable w/ the `toolbar toggle`) command.
