### ISSUE TITLE
we should cap the number of reported errors

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#79]
For performance reasons, and because after a certain number they're not really useful to the user any more. Perhaps something like 100 for an individual file, and 500 for a project? We'll need to be careful to do it in a way that's consistent, like taking the first x from a file, sorted by offset in the file. Probably also add one more marker, `Additional errors not reported.`.

**Comment by sethladd** [comment]
+1 to something like "XX errors displayed, out of YY".

Curious, where does the perf issue hit? Displaying the error in the source code? Or the pure communication between the plugin and the AS? or other...

**Comment by devoncarew** [comment]
I think it's expensive to change the errors for the project - possibly an optimization opportunity in the linter plugin. Not sure why it's slow, but we can mitigate it by 1) not setting too many errors, and 2) not setting them too frequently.
