### ISSUE TITLE
change our error caping mechanism to only work per-project

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#801]
Right now we cap the number of errors per-project, and per-session (all projects combined). We should just cap per-project, so one project with a lot of errors won't affect the other projects.

**Comment by apwilson** [comment]
Some context.  I have ~10 projects open at a time.  If one of those projects has > 500 errors, no errors are ever shown for the remaining ~9 projects which gives the impression the analyzer has stopped running.  One bad project shouldn't ruin the bunch.
