### ISSUE TITLE
Disable auto-triggering of completion in Dart files

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#81]
Consider this case:

```
Map data = {
  'one': 1,
  'two': 2// <== right here, put a comma and then hit enter
};
```

Expected: a comma and cursor inserted into next line

Actual: code completion window pops up, and enter selects the top result, and the result is inserted.

![jul 17 2015 10 02](https://cloud.githubusercontent.com/assets/5479/8752716/041f3fd8-2c6b-11e5-8881-61ad76f5d97a.gif)

**Comment by sethladd** [comment]
cc @iposva-google

**Comment by sethladd** [comment]
Curious if we can bump up the priority.

Code completion is pretty aggressive. Also happens at the end of lines, too often.

We're hitting Escape (to disable the code completion) too often... 

Thanks for taking a look!

**Comment by devoncarew** [comment]
I'll put a fix in for the completion auto-delay. I suspect there's a bigger issue where atom autocomplete-plus UI is not really expecting latency in the returned completions, and the analysis server has some non-zero latency.

**Comment by pstjvn** [comment]
This is possibly number one issue. I am not sure about it but is it possible to call autocompletion with ctrl+space only (i.e. disable it while regular typing) until this is fixed?

**Comment by devoncarew** [comment]
There's a setting in the `autocomplete-plus` package to control just this. We've gotten a lot of feedback about this issue. It may be the right call to disable auto-triggering, at least for dart files.

**Comment by sethladd** [comment]
Did we ever disable auto-triggering for Dart files?

**Comment by devoncarew** [comment]
We:
- disable auto-completion in certain unlikely places (immediately after `;` or `,`)
- change the default delay from 100ms to 500ms

We experimented with disabling autocompletion completely for dart files, but got feedback that this was on the whole undesired.

**Comment by sethladd** [comment]
Sgtm thanks for the update
