### ISSUE TITLE
Markdown code blocks highlighted incorrectly in documentation comments

### ISSUE THREAD

**Issue by hermanbergwerf** [dart-atom/dartlang#811]
Not sure if this is related to this plugin, but this has been happening for quite a while now. You can reproduce it by typing the same comment as shown below in Atom.

![issue-screenshot](https://cloud.githubusercontent.com/assets/4458965/13380256/a71b65c4-de3e-11e5-9694-f6d679c8a24d.png)

If that's possible real syntax highlighting in the code block (in this case YAML) would be very nice!

**Comment by devoncarew** [comment]
It would be interesting to see how dartdoc treats that documentation - whether it considers it yaml or not. I don't think code fences (triple backquotes) are part of dartdoc. Lines that have 5 leading spaces (1 after the /// comment marker, and 4 to indicate a code section, are treated as Dart source code.

This may be as-designed -

**Comment by hermanbergwerf** [comment]
In theory it should support markdown (I've seen it working as well). I
actually didn't know markdown supported code blocks like in ReST, I do
actually like this style.
