### ISSUE TITLE
Inconsistent syntax highlighting between getter and setter

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#83]
I would imagine that highlighting setter is the same as the getter?

![screen shot 2015-07-17 at 5 09 44 pm](https://cloud.githubusercontent.com/assets/5479/8759338/be5b8a9c-2ca6-11e5-9f02-b2720eb73acb.png)

Note how length is highlighted two different ways.

**Comment by radicaled** [comment]
The grammar is probably highlighting it as a function due to the parens after `length`.

So we should either add `=>` so that the grammar recognizes that as a function, or alter the way we colorize functions to exclude any that look like `set $WORD(`.

**Comment by devoncarew** [comment]
With the PR:

<img width="287" alt="screen shot 2015-07-19 at 3 13 09 pm" src="https://cloud.githubusercontent.com/assets/1269969/8768114/d7df3670-2e28-11e5-83a8-2faa649bf839.png">

**Comment by sethladd** [comment]
Thanks!
