### ISSUE TITLE
add the ability to toggle break-on-all exceptions

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#838]
Add the ability to toggle break-on-all exceptions.
- probably as a dropdown expanding menu in the debugger view
- the setting should persist between sessions

**Comment by pulyaevskiy** [comment]
Is there any workaround currently to disable this behavior somehow?

**Comment by devoncarew** [comment]
You can toggle it in the settings for the `dartlang` plugin.

**Comment by pulyaevskiy** [comment]
Should've looked there in the first place. Thanks so much! 

P.S: Also found experimental "type information tooltip", which is amazing!
