### ISSUE TITLE
Error view should not be shown when empty

### ISSUE THREAD

**Issue by niedzielski** [dart-atom/dartlang#848]
The error view window is shown by default, even when empty, which affects every project Dart or non-Dart alike. e.g., I open a Java project and the Dart error view is shown for _every_ file opened. I've had to disable the view in settings but would prefer for the default to be smarter.

**Comment by devoncarew** [comment]
You can also click on the error count in the status line to toggle the view.

**Comment by niedzielski** [comment]
Hm, actually it looks like disabling the settings doesn't work when I relaunch Atom (v1.5.4). I also don't seem to have any luck when clicking any of the buttons at the bottom of the window (File 0, Project 0, No Issues, ...).

![screenshot from 2016-03-07 16-57-18](https://cloud.githubusercontent.com/assets/1071806/13587507/08d02604-e486-11e5-9922-43bf3be62a51.png)
![screenshot from 2016-03-07 16-58-18](https://cloud.githubusercontent.com/assets/1071806/13587508/08d057d2-e486-11e5-9c3c-e0c45fbb6268.png)

**Comment by devoncarew** [comment]
Those `[File][Project]` status line things are contributed by the linter package.

You should be able to change the settings in the pref page for the 'dartlang' package.

**Comment by niedzielski** [comment]
Nice! So I actually want "show errors view" enabled under Dart settings and I just needed to tap the new "no errors" button at the bottom. Thanks!!
