### ISSUE TITLE
it's possible to get two jobs status indicators displaying at the same time

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#85]
<img width="222" alt="screen shot 2015-07-18 at 4 20 50 pm" src="https://cloud.githubusercontent.com/assets/1269969/8763903/343c3050-2d69-11e5-8d1f-1783c761f159.png">

To repro, disable the plugin and re-enable it.

**Comment by radicaled** [comment]
Is this fixed in #85?
