### ISSUE TITLE
Can't seem to turn on "configurable imports" support

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#851]
I'm using Atom to write Flutter code, and Flutter's VM supports configurable imports. How can I turn this option on, for Atom?

Thanks!

**Comment by sethladd** [comment]
cc @collinjackson

**Comment by devoncarew** [comment]
You'll need to update the _embedder.yaml file in the engine, w/ the new analysis option.

**Comment by sethladd** [comment]
Is the idea to not expose these options via Atom UI?  If so, please close this issue, and I'll add a new issue over in Flutter to update our _embedder.yaml

Thanks!

**Comment by devoncarew** [comment]
Yeah, we should use `.analysis_options`, `_embedder.yaml`, or just have the analyzer default to supporting configurable imports. It should be a no-op for code that's not using them.
