### ISSUE TITLE
Analyzer is analyzing packages in ".gitignored" packages

### ISSUE THREAD

**Issue by abarth** [dart-atom/dartlang#855]
When working in the Flutter repository, I have some packages in the `//bin/cache/pkg` that are generating hundreds of analyzer warnings.  These packages are gitignored and ideally won't log errors.

/cc @devoncarew

**Comment by abarth** [comment]
Example error:
```
The library '"dart:_internal"' is internal and cannot be importedbin/cache/pkg/sky_engine/dart_sdk/async/async.dart, line 95
```

**Comment by devoncarew** [comment]
I shouldn't be finding them. Is this when you're opening atom at the top level of the flutter repo? I'll try and repro.

**Comment by devoncarew** [comment]
(can repro)
