### ISSUE TITLE
Dart SDK location changed back to flutter on restart

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#866]
I keep trying to change my Dart SDK, but the plugin keeps changing it back.

- Go to Dart->Packages->Dart Settings
- The Dart SDK is:
  /Users/skybrian/software/flutter/bin/cache/dart-sdk
- I change it to what I want it to be:
 /Users/skybrian/dart/sdkwork/sdk/xcodebuild/ReleaseX64/dart-sdk
- I see a message that the SDK was successfully switched.
- Select Atom->Open Your Config
- See that the config file entry was changed (dartlang->sdkLocation).
- Quit Atom
- Open Atom

Now the SDK location is changed back to Flutter. (In the config file it was changed too.)
I tried disabling the Flutter plugin. Didn't help.
The workaround seems to be to rename the Flutter SDK directory, so that the old Dart SDK location is no longer valid.

Atom 1.5.4
dartlang 0.6.5

**Comment by devoncarew** [comment]
Thanks - this is fixed in master and should go out ~monday.
