### ISSUE TITLE
Open bracket ([) character invokes rebuild of atom plugins

### ISSUE THREAD

**Issue by geekrumper** [dart-atom/dartlang#870]
This issue happens on a swiss-german keyboard layout and only if I have dartlang installed in atom.

atom version: 1.5.4
package version (dartlang): 0.6.6 
running on windows 7 pro 64 bit

pressing the keystroke on an empty file the following notifications show up:

![atom_dartlang](https://cloud.githubusercontent.com/assets/662318/13789972/999b3cbc-eae6-11e5-90ee-83a87cc5c44b.png)

pressing the keystroke in a file which has content, reacts like this:

![atom_dartlang2](https://cloud.githubusercontent.com/assets/662318/13790028/c444c3ca-eae6-11e5-86d0-c25477fbe5d6.png)

By removing the package, the problem is resolved. But that's surely not my intent. Maybe the following information might be helpful:

I have to press "ALT-GR + open bracket" (right ALT) to type that character.

**Comment by lukechurch** [comment]
cc @danrubel as discussed

**Comment by geekrumper** [comment]
deactivating dartlang keybindings is a workaround for me. But I haven't found any command (dartlang) which would match the binding nor the process that's being invoked.

**Comment by devoncarew** [comment]
I think we should just contribute this keybinding when the right projects exist in the workspace - this will make the (plugin dev. only option) less user facing.

**Comment by geekrumper** [comment]
@devoncarew is correct, because according to wikipedia "CTRL+ALT" (two buttons) and "ALT GR" (stands for alt graph and is one button) are the same.

https://en.wikipedia.org/wiki/AltGr_key#Control_.2B_Alt_as_a_substitute

**Comment by devoncarew** [comment]
Looks like this is still causing issues for some keyboards.

**Comment by devoncarew** [comment]
@geekrumper, can you try a fix locally to see if this works. can you Remove this line: https://github.com/dart-atom/dartlang/blob/master/keymaps/atom-dart.cson#L23 from the dartlang keymap. You can test that w/ a local clone of the rep, or probably just by editing the file in your cached local copy (on a mac, in ~/.atom/packages/dartlang/).

**Comment by geekrumper** [comment]
@devoncarew, this workaround works perfectly!!!

keymap binding removed
![keymaps_atom-dart cson](https://cloud.githubusercontent.com/assets/662318/14012701/c546703a-f1a7-11e5-8c50-7786a180ab75.png)

keymaps for dartlang activated
![atom_seetings](https://cloud.githubusercontent.com/assets/662318/14012714/db159918-f1a7-11e5-8764-2a668840198f.png)

![atom_dartlang_keymaps](https://cloud.githubusercontent.com/assets/662318/14012716/df38c308-f1a7-11e5-9c4f-71fec20c10b4.png)

And do not forget to restart atom.
