### ISSUE TITLE
Updating doc comments

### ISSUE THREAD

**Issue by jacehensley-wf** [dart-atom/dartlang#889]
When I update a doc comment and look at the documentation (fn+f1) it is not updated until I reanalyze sources. 

I would expect:
- Editing doc comments to cause a reanalyze.

__OR__

- Getting documentation to always fetch the current doc comment and render it on the fly. (Not sure if this would be expensive).

**Comment by jacehensley-wf** [comment]
Come to think of it should this be moved to dart-lang/sdk?

**Comment by devoncarew** [comment]
This is likely an issue with the underlying analysis server (hosted in the dart-lang/sdk repo). It _should_ update doc comments w/o a reanalyze (and does for me locally).

**Comment by jacehensley-wf** [comment]
Hmm, yeah it does not work for me locally, I am on SDK 1.15 if that makes a difference. Okay I'll open an issue in the sdk repo.

**Comment by jacehensley-wf** [comment]
Closing issue moved to [dart-lang/sdk](https://github.com/dart-lang/sdk/issues/26216).
