### ISSUE TITLE
Code completing after a named param shows me methods that return the wrong thing

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#904]
![screen shot 2016-03-24 at 4 28 55 pm](https://cloud.githubusercontent.com/assets/5479/14034135/9ac62f04-f1dd-11e5-9068-97e2eb7e67ff.png)

Atom 1.6.0, dartlang 0.6.8, SDK 1.15.0-dev.5.0 running on macos.

**Comment by devoncarew** [comment]
This will need to be moved over to the sdk repo.

**Comment by sethladd** [comment]
This issue was moved to dart-lang/sdk#26092
