### ISSUE TITLE
Find Type doesn't find "ThemeData"

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#906]
And yet, ThemeData is a type. I'm pretty sure. :)

![screen shot 2016-03-24 at 4 38 36 pm](https://cloud.githubusercontent.com/assets/5479/14034278/03770964-f1df-11e5-90b2-e7229228064c.png)

**Comment by devoncarew** [comment]
Totally; some details here: https://github.com/dart-atom/dartlang/issues/897, but this has been fixed in the analysis server and will make it's way into the next dev sdk release.

**Comment by sethladd** [comment]
Ah, great! Thanks for the quick response.
