### ISSUE TITLE
Code completion doesn't show optional params

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#91]
![screen shot 2015-07-20 at 10 01 52 am](https://cloud.githubusercontent.com/assets/5479/8781852/7e58cfb4-2ec6-11e5-9b3f-85b3f4354659.png)

Expected: something like `sort([int compare(Field a, Field b)])`

**Comment by devoncarew** [comment]
Can you re-file this against the analysis server (sdk) repo?

**Comment by devoncarew** [comment]
Ah, nevermind. We can control the presentation here; I thought the issue was to do with not having the info at all.

**Comment by sethladd** [comment]
I tried it in Dart Pad, and it looks pretty good there:

![screen shot 2015-07-20 at 10 14 24 am](https://cloud.githubusercontent.com/assets/5479/8782115/227a1e26-2ec8-11e5-9188-95f0e8d93574.png)

**Comment by lukechurch** [comment]
+1, this is starting to cause me problems on a semi-regular basis now I'm using Atom more.
