### ISSUE TITLE
Toggle type hierarchy and show usages by hotkey

### ISSUE THREAD

**Issue by Aetet** [dart-atom/dartlang#918]
It would be very handful toggle type hierarchy show usages by hotkey, as vim-mode user I prefer keyboard shortcuts and not touch mouse.

**Comment by devoncarew** [comment]
Type hierarchy is `F4`; find references you can get to through the atom command pallette. They can both be closed by hitting escape twice. Thanks for the feedback!

And, atom has a lot of default key bindings - these are fully configurable. If you see a command you like in the command pallete (search for dartlang), you can easily set up a binding for it.

**Comment by Aetet** [comment]
But I can't close them, because I have vim mode. And double escape does not work for me.

**Comment by Aetet** [comment]
Found workaround with remapping `core:cancel` command at atom to my own hotkeys.
