### ISSUE TITLE
performance problem with the `'dartlang:newline'` command?

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#92]
Performance problem with the `'dartlang:newline'` command?

**Comment by devoncarew** [comment]
Though, possibly a red herring.

**Comment by sethladd** [comment]
Profile here: https://dl.dropboxusercontent.com/u/316685/CPU-20150720T155112.cpuprofile

**Comment by sethladd** [comment]
I disabled emmet... will continue to keep an eye on it.

**Comment by devoncarew** [comment]
We should re-enable the dartdoc typing command then - it improves the dartdoc editing experience

**Comment by devoncarew** [comment]
Will re-add this in https://github.com/dart-atom/dartlang/pulls
