### ISSUE TITLE
If analysis server is turned off or not working, don't show options that require it

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#93]
For example, if AS is turned off/not working/etc, don't show "right click | jump to definition". Because that won't work :)

**Comment by radicaled** [comment]
Do you mean "Go to Definition?"

That's provided by the `symbols-view` plugin distributed by Atom, and I don't think there's a way we can turn that on and off on a per-file basis.

**Comment by radicaled** [comment]
We can do what TypeScript does, which is basically override the command and display a notification message if there's a problem, though.

**Comment by devoncarew** [comment]
I'm not sure we're going to be able to get to this one.
