### ISSUE TITLE
'Go to declaration' doesn't work

### ISSUE THREAD

**Issue by vlidholt** [dart-atom/dartlang#95]
Right clicking a variable or function name and selecting 'Go to declaration' doesn't work.

**Comment by sethladd** [comment]
works for me. Where are you trying to go? And from where?  (we can test it out)

**Comment by DanielJoyce** [comment]
Sometimes works for me, sometimes doesn't. Maybe its just a too-long pause?

**Comment by DanielJoyce** [comment]
``` dart
class Derp extends Foo {

  Qux qux = null;

}
```

If Qux and Foo are all properly defined and imported, hitting F3 when cursor is in Foo and Qux works for both

Right clicking Qux and choosing "Go to Declaration" works

Right clicking Foo and choosing "Go to Declaration" doesn't

TL;DR:
"Go to Declaration" context menu item  doesn't work for types used in class declaration

atom editor 1.0.2
dartlang 0.3.4

**Comment by devoncarew** [comment]
I can't repro this and it's an older bug. Closing this; we can re-open if it's still impacting people.
