### ISSUE TITLE
No summary of hints/errors/warnings in "problems view"

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#98]
I'd love to see a summary of how many hints/errors/warnings I have. Right now, it's a flat list and can scroll out of view. I don't know if I have any errors or warnings, because all I see is a list of hints.

![screen shot 2015-07-20 at 4 27 57 pm](https://cloud.githubusercontent.com/assets/5479/8789948/b0b8cca8-2efc-11e5-89e3-e3c87de65d50.png)

I'd love to see something like: 24 hints, 2 warnings, 0 errors. This way, I don't get stressed from the list of hints that I see.

**Comment by DanielJoyce** [comment]
Somehow I have hidden my problem view and can't get it back. How can I show it again? Or is this a bug?

**Comment by devoncarew** [comment]
The settings to hide and show it are in the `linter` plugin. You can see them in the Settings page, in the packages section.

**Comment by devoncarew** [comment]
Closing this as I think it's largely a dup of #112.
