### ISSUE TITLE
analysis server process consumes lots of RAM

### ISSUE THREAD

**Issue by ianloic** [dart-atom/dartlang#983]
On my Mac it's currently consuming 6.14GB of RAM.

That seems like a lot. After restarting it the RAM usage seems to creep up quite quickly.

**Comment by devoncarew** [comment]
Totally agree. @bwilkerson, it would be good to get the analysis server's ram usage under a continuous benchmark.

**Comment by devoncarew** [comment]
This issue was moved to dart-lang/sdk#26442
