### ISSUE TITLE
Synced-Sidebar seems to already be included

### ISSUE THREAD

**Issue by Zectbumo** [dart-atom/dartlang#986]
On your website https://dart-atom.github.io/dartlang/ it recommends getting Synced-Sidebar but I think Atom already pulls this in automatically. I can't seem to even remove it because it will reinstall when I relaunch.  I don't think it's worth mentioning on your website since it made me hunt for something that I already have and can't seem to remove if I wanted to.

**Comment by devoncarew** [comment]
We'll update the docs, thanks!

To prevent the re-installation, you can disable the synced-sidebar plugin. It won't be active, and the dartlang plugin won't try and reinstall it. Hope that helps!
