### ISSUE TITLE
Handle `pub run test` better

### ISSUE THREAD

**Issue by jakemac53** [dart-atom/dartlang#987]
Today you can actually right click on your pubspec.yaml, select "Pub Run..." and then type in "test" to the dialog, and it will run the tests using the test runner.

The issue is the output, for all success messages they seem to get output on a single line. Errors actually do seem to get their own line though, so its not totally unmanageable.

Is there anything better we can do here?

**Comment by devoncarew** [comment]
It looks like `test` is only producing one line. It's not actually using eols to separate lines, but guessing at the width of a console, and appending n spaces as separators between lines instead.

Things look good if you run `test -rexpanded` and event better with `test -rexpanded --no-color`.

**Comment by devoncarew** [comment]
Ah, no, there was an error in the line-splitting algorithm.

**Comment by devoncarew** [comment]
@jakemac53, I'd forgotten, but you can also run tests for a project by calling the atom command `run tests`.
