### ISSUE TITLE
Clicking on the red "X 46 issues" takes me to... not sure

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#99]
Not really sure what "X 46 issues" at the bottom of my Atom window are telling me. 46 issues in my whole project?

When I click it, I'm taken to what seems like a random file. For example:

![screen shot 2015-07-20 at 4 32 47 pm](https://cloud.githubusercontent.com/assets/5479/8789963/fca32ea6-2efc-11e5-955d-9cf3a83cca8e.png)

Why this file?

Is there a way to see a list of all errors in my project (so I can clean those up), and then all warnings, and then all hints ?

**Comment by radicaled** [comment]
The bottom panel is provided by AtomLinter/linter; clicking on the # of issues navigates you to the next issue is knows about. In this case, it's the first issue in the list: the bad import.

**Comment by devoncarew** [comment]
Yeah, and those `file` and `project` items down there act sort of like tabs. Selecting `project` will show all known issues for all files. `file` will show just for the current file. I would like something that focused more on issues for the current file and the project that contained it (not the whole workspace, just the project).

**Comment by radicaled** [comment]
They're apparently renamed to `atom-community/linter` (no idea why). They're pretty responsive; maybe open a feature request there? https://github.com/atom-community/linter

**Comment by sethladd** [comment]
Thanks. Is there such a thing as a single list of all hints/warnings/errors for a project ? I'm looking for a way to triage all my issues, and seeing a single list would be helpful.

**Comment by radicaled** [comment]
It's the project tab.

It's not obvious, but you can scroll with the mouse wheel.

**Comment by devoncarew** [comment]
We'll track problem view related issues hee: #112. Agree that it needs a UX re-design. Either in `dartlang`, `linter`, or some combination.
